from pump_data.schema.pump_lov import PumpDetail_schema
from datetime import datetime
from typing import Optional
from ninja import Schema
from uuid import UUID , uuid4
from pydantic import Field

class EngineerReportPayLoad_schema(Schema):
    report_id : Optional[UUID]=Field(default_factory=uuid4)
    pump_detail : Optional[UUID]=None
    user_detail : Optional[str]=None
    created_at: Optional[datetime] = None
    created_by: Optional[str] = None
    updated_at: datetime
    updated_by: Optional[str] = None

class EngineerReport_schema(Schema):
    pump_detail : Optional[str]=None
    user_detail : Optional[str]=None
    report_name : Optional[str]=None
    report_detail : Optional[str]=None
    remarks : Optional[str]=None
    report_file : Optional[str]=None
    created_at: Optional[datetime] = None
    created_by: Optional[str] = None
    updated_at: datetime
    updated_by: Optional[str] = None

class EngineerReportCheck_schema(Schema):
    pump_id : Optional[str]=None
    doc_customer :Optional[str]=None
    doc_no: Optional[str]=None
    doc_number_engineer: Optional[str]=None
    status: Optional[str]=None
    created_at: Optional[datetime] = None
    created_by: Optional[str] = None
    updated_at: datetime
    updated_by: Optional[str] = None

class EngineerReportCheckCal_schema(Schema):
    check_id : Optional[str] = None
    test_speed : Optional[str] = None
    test_speed_unit : Optional[str] = None
    flow_ope : Optional[str] = None
    flow_ope_unit : Optional[str] = None
    suction_pres_ope : Optional[str] = None
    suction_pres_ope_unit : Optional[str] = None
    discharge_pres_ope : Optional[str] = None
    discharge_pres_ope_unit : Optional[str] = None
    diff_pres_ope : Optional[str] = None
    diff_pres_ope_unit : Optional[str] = None
    bearing_housing_temp : Optional[str] = None
    bearing_housing_temp_unit : Optional[str] = None
    current_i1_ope : Optional[str] = None
    current_i1_ope_unit : Optional[str] = None
    current_i2_ope : Optional[str] = None
    current_i2_ope_unit : Optional[str] = None
    current_i3_ope : Optional[str] = None
    current_i3_ope_unit : Optional[str] = None
    i_avg_ope : Optional[str] = None
    i_avg_ope_unit : Optional[str] = None
    v_avg_ope : Optional[str] = None
    v_avg_ope_unit : Optional[str] = None
    motor_power : Optional[str] = None
    motor_power_unit : Optional[str] = None
    shaft_ope : Optional[str] = None
    shaft_ope_unit : Optional[str] = None
    hyd_power_measure : Optional[str] = None
    head_ope : Optional[str] = None
    hyd_power_measure_unit : Optional[str] = None
    head_ope_unit : Optional[str] = None
    head_shut : Optional[str] = None
    head_shut_unit : Optional[str] = None
    head_max : Optional[str] = None
    head_max_unit : Optional[str] = None
    voltage_uv : Optional[str] = None
    voltage_vw : Optional[str] = None
    voltage_uw : Optional[str] = None
    voltage_un : Optional[str] = None
    voltage_vn : Optional[str] = None
    voltage_wn : Optional[str] = None
    insulation_uv : Optional[str] = None
    insulation_winding_ux : Optional[str] = None
    insulation_vw : Optional[str] = None
    insulation_winding_vy : Optional[str] = None
    insulation_uw : Optional[str] = None
    insulation_winding_wz : Optional[str] = None
    insulation_un : Optional[str] = None
    insulation_vn : Optional[str] = None
    insulation_wn : Optional[str] = None
    current_u1 : Optional[str] = None
    current_v1 : Optional[str] = None
    current_w1 : Optional[str] = None
    current_u2 : Optional[str] = None
    current_v2 : Optional[str] = None
    current_w2 : Optional[str] = None
    Temp_u1 : Optional[str] = None
    Temp_v1 : Optional[str] = None
    Temp_w1 : Optional[str] = None
    Temp_u2 : Optional[str] = None
    Temp_v2 : Optional[str] = None
    Temp_w2 : Optional[str] = None
    env_temp : Optional[str] = None
    env_temp_unit : Optional[str] = None
    liquid_temp : Optional[str] = None
    liquid_temp_unit : Optional[str] = None
    npsha : Optional[str] = None
    npsha_unit : Optional[str] = None
    npsha_actual : Optional[str] = None
    npsha_actual_unit : Optional[str] = None
    suction_fluid_velo : Optional[str] = None
    suction_fluid_velo_unit : Optional[str] = None
    discharge_fluid_velo : Optional[str] = None
    discharge_fluid_velo_unit : Optional[str] = None
    remarks : Optional[str] = None

class ReportCheckCalPayload_schema(Schema):
    pump_data : Optional[PumpDetail_schema] = None
    report_data : Optional[EngineerReportCheckCal_schema] = None

class EngineerReportCheckVibe_schema(Schema):
    check_id : Optional[str] = None
    v_pump_de_h : Optional[str] = None
    v_pump_de_h_unit : Optional[str] = None
    v_pump_de_v : Optional[str] = None
    v_pump_de_v_unit : Optional[str] = None
    v_pump_de_a : Optional[str] = None
    v_pump_de_a_unit : Optional[str] = None
    v_pump_nde_h : Optional[str] = None
    v_pump_nde_h_unit : Optional[str] = None
    v_pump_nde_v : Optional[str] = None
    v_pump_nde_v_unit : Optional[str] = None
    v_pump_nde_a : Optional[str] = None
    v_pump_nde_a_unit : Optional[str] = None
    v_motor_de_h : Optional[str] = None
    v_motor_de_h_unit : Optional[str] = None
    v_motor_de_v : Optional[str] = None
    v_motor_de_v_unit : Optional[str] = None
    v_motor_de_a : Optional[str] = None
    v_motor_de_a_unit : Optional[str] = None
    v_motor_nde_h : Optional[str] = None
    v_motor_nde_h_unit : Optional[str] = None
    v_motor_nde_v : Optional[str] = None
    v_motor_nde_v_unit : Optional[str] = None
    v_motor_nde_a : Optional[str] = None
    v_motor_nde_a_unit : Optional[str] = None
    a_pump_de_h : Optional[str] = None
    a_pump_de_h_unit : Optional[str] = None
    a_pump_de_v : Optional[str] = None
    a_pump_de_v_unit : Optional[str] = None
    a_pump_de_a : Optional[str] = None
    a_pump_de_a_unit : Optional[str] = None
    a_pump_nde_h : Optional[str] = None
    a_pump_nde_h_unit : Optional[str] = None
    a_pump_nde_v : Optional[str] = None
    a_pump_nde_v_unit : Optional[str] = None
    a_pump_nde_a : Optional[str] = None
    a_pump_nde_a_unit : Optional[str] = None
    a_motor_de_h : Optional[str] = None
    a_motor_de_h_unit : Optional[str] = None
    a_motor_de_v : Optional[str] = None
    a_motor_de_v_unit : Optional[str] = None
    a_motor_de_a : Optional[str] = None
    a_motor_de_a_unit : Optional[str] = None
    a_motor_nde_h : Optional[str] = None
    a_motor_nde_h_unit : Optional[str] = None
    a_motor_nde_v : Optional[str] = None
    a_motor_nde_v_unit : Optional[str] = None
    a_motor_nde_a : Optional[str] = None
    a_motor_nde_a_unit : Optional[str] = None
    temp_pump_nde : Optional[str] = None
    temp_pump_nde_unit : Optional[str] = None
    temp_pump_de : Optional[str] = None
    temp_pump_de_unit : Optional[str] = None
    temp_motor_nde : Optional[str] = None
    temp_motor_nde_unit : Optional[str] = None
    temp_motor_de : Optional[str] = None
    temp_motor_de_unit : Optional[str] = None
    env_vibration : Optional[str] = None
    env_vibration_unit : Optional[str] = None

class EngineerReportCheckVisual_schema(Schema):
    check_id : Optional[str] = None
    axial_hand_check : Optional[str] = 'Not Pass'
    axial_hand_remark : Optional[str] = None
    electricity_check : Optional[str] = 'Not Pass'
    electricity_remark : Optional[str] = None
    service_check : Optional[str] = 'Not Pass'
    service_remark : Optional[str] = None
    leakage_check : Optional[str] = 'Not Pass'
    leakage_remark : Optional[str] = None
    oil_grease_run_check : Optional[str] = 'Not Pass'
    oil_grease_run_remark : Optional[str] = None
    mechanical_run_check : Optional[str] = 'Not Pass'
    mechanical_run_remark : Optional[str] = None
    corrosion_run_check : Optional[str] = 'Not Pass'
    corrosion_run_remark : Optional[str] = None
    suction_valve_run_check : Optional[str] = 'Not Pass'
    suction_valve_run_remark : Optional[str] = None
    discharge_valve_run_check : Optional[str] = 'Not Pass'
    discharge_valve_run_remark : Optional[str] = None
    painting_run_check : Optional[str] = 'Not Pass'
    painting_run_remark : Optional[str] = None
    electric_connectivity_run_check : Optional[str] = 'Not Pass'
    electric_connectivity_run_remark : Optional[str] = None
    service_piping_run_check : Optional[str] = 'Not Pass'
    service_piping_run_remark : Optional[str] = None
    bolt_nut_run_check : Optional[str] = 'Not Pass'
    bolt_nut_run_remark : Optional[str] = None
    barrier_fluid_run_pres_check : Optional[str] = 'Not Pass'
    barrier_fluid_run_pres_remark : Optional[str] = None
    remarks_check : Optional[str] = 'Not Pass'

    bolt_check : Optional[str] = 'Not Pass'
    bolt_remark : Optional[str] = None
    electrical_check : Optional[str] = 'Not Pass'
    electrical_remark : Optional[str] = None
    corrosion_check : Optional[str] = 'Not Pass'
    corrosion_remark : Optional[str] = None
    oil_grease_check : Optional[str] = 'Not Pass'
    oil_grease_remark : Optional[str] = None
    oil_check : Optional[str] = 'Not Pass'
    oil_remark : Optional[str] = None
    painting_check : Optional[str] = 'Not Pass'
    painting_remark : Optional[str] = None
    cleanness_check : Optional[str] = 'Not Pass'
    cleanness_remark : Optional[str] = None
    chemical_clogging_check : Optional[str] = 'Not Pass'
    chemical_clogging_remark : Optional[str] = None
    suction_valve_check : Optional[str] = 'Not Pass'
    suction_valve_remark : Optional[str] = None
    discharge_valve_check : Optional[str] = 'Not Pass'
    discharge_valve_remark : Optional[str] = None
    hydraulic_air_check : Optional[str] = 'Not Pass'
    hydraulic_air_remark : Optional[str] = None
    air_supply_check : Optional[str] = 'Not Pass'
    air_supply_remark : Optional[str] = None
    air_filter_check : Optional[str] = 'Not Pass'
    air_filter_remark : Optional[str] = None
    air_filter_condense_check : Optional[str] = 'Not Pass'
    air_filter_condense_remark : Optional[str] = None
    mechanical_check : Optional[str] = 'Not Pass'
    mechanical_remark : Optional[str] = None
    coupling_check : Optional[str] = 'Not Pass'
    coupling_remark : Optional[str] = None
    gap_check : Optional[str] = 'Not Pass'
    gap_remark : Optional[str] = None
    seal_check : Optional[str] = 'Not Pass'
    seal_remark : Optional[str] = None
    alignment_check : Optional[str] = 'Not Pass'
    alignment_remark : Optional[str] = None
    rotate_hand_check : Optional[str] = 'Not Pass'
    rotate_hand_remark : Optional[str] = None
    rotating_check : Optional[str] = 'Not Pass'
    rotating_remark : Optional[str] = None
    noise_run_check : Optional[str] = 'Not Pass'
    noise_run_remark : Optional[str] = None
    noise_check : Optional[str] = 'Not Pass'
    noise_remark : Optional[str] = None
    oil_run_check : Optional[str] = 'Not Pass'
    oil_run_remark : Optional[str] = None
    leakage_run_check : Optional[str] = 'Not Pass'
    leakage_run_remark : Optional[str] = None
    impeller_stutter_check : Optional[str] = 'Not Pass'
    impeller_stutter_remark : Optional[str] = None
    cavitation_run_check : Optional[str] = 'Not Pass'
    cavitation_run_remark : Optional[str] = None
    other_leakage_check : Optional[str] = 'Not Pass'
    other_leakage_remark : Optional[str] = None
    non_re_valve_check : Optional[str] = 'Not Pass'
    non_re_valve_remark : Optional[str] = None

class EngineerReportCheckResult_schema(Schema):
    check_id : Optional[str] = None
    speed_suggest : Optional[str] = None
    flow_suggest : Optional[str] = None
    npshr_suggest : Optional[str] = None
    velocity_suggest : Optional[str] = None
    boiling_point_suggest : Optional[str] = None
    current_suggest : Optional[str] = None
    api_suggest : Optional[str] = None
    buffer_suggest : Optional[str] = None
    bearing_suggest : Optional[str] = None
    vibration_suggest : Optional[str] = None
    timestamp : Optional[str] = None
    range_30_110_result : Optional[str] = None
    range_30_110_suggest : Optional[str] = None
    range_30_110_remark : Optional[str] = None
    npshr_npsha_result : Optional[str] = None
    npshr_npsha_suggest : Optional[str] = None
    npshr_npsha_remark : Optional[str] = None
    pump_standard_result : Optional[str] = None
    pump_standard_suggest : Optional[str] = None
    pump_standard_remark : Optional[str] = None
    power_result : Optional[str] = None
    power_suggest : Optional[str] = None
    power_remark : Optional[str] = None
    fluid_temp_result : Optional[str] = None
    fluid_temp_suggest : Optional[str] = None
    fluid_temp_remark : Optional[str] = None
    bearing_temp_result : Optional[str] = None
    bearing_temp_suggest : Optional[str] = None
    bearing_temp_remark : Optional[str] = None
    v_pump_de_h_result : Optional[str] = None
    v_pump_de_v_result : Optional[str] = None
    v_pump_de_a_result : Optional[str] = None
    v_pump_nde_h_result : Optional[str] = None
    v_pump_nde_v_result : Optional[str] = None
    v_pump_nde_a_result : Optional[str] = None
    v_motor_de_h_result : Optional[str] = None
    v_motor_de_v_result : Optional[str] = None
    v_motor_de_a_result : Optional[str] = None
    v_motor_nde_h_result : Optional[str] = None
    v_motor_nde_v_result : Optional[str] = None
    v_motor_nde_a_result : Optional[str] = None
    a_pump_de_h_result : Optional[str] = None
    a_pump_de_v_result : Optional[str] = None
    a_pump_de_a_result : Optional[str] = None
    a_pump_nde_h_result : Optional[str] = None
    a_pump_nde_v_result : Optional[str] = None
    a_pump_nde_a_result : Optional[str] = None
    a_motor_de_h_result : Optional[str] = None
    a_motor_de_v_result : Optional[str] = None
    a_motor_de_a_result : Optional[str] = None
    a_motor_nde_h_result : Optional[str] = None
    a_motor_nde_v_result : Optional[str] = None
    a_motor_nde_a_result : Optional[str] = None
    v_pump_suggest : Optional[str] = None
    v_pump_remark : Optional[str] = None
    v_motor_suggest : Optional[str] = None
    v_motor_remark : Optional[str] = None
    a_pump_suggest : Optional[str] = None
    a_pump_remark : Optional[str] = None
    a_motor_suggest : Optional[str] = None
    a_motor_remark : Optional[str] = None

class EngineerReportCheckResultSubmit_schema(Schema):
    check_id : Optional[str] = None
    test_speed : Optional[str] = None
    test_speed_unit : Optional[str] = None
    flow_ope : Optional[str] = None
    flow_ope_unit : Optional[str] = None
    suction_pres_ope : Optional[str] = None
    suction_pres_ope_unit : Optional[str] = None
    discharge_pres_ope : Optional[str] = None
    discharge_pres_ope_unit : Optional[str] = None
    diff_pres_ope : Optional[str] = None
    diff_pres_ope_unit : Optional[str] = None
    current_i1_ope : Optional[str] = None
    current_i1_ope_unit : Optional[str] = None
    current_i2_ope : Optional[str] = None
    current_i2_ope_unit : Optional[str] = None
    current_i3_ope : Optional[str] = None
    current_i3_ope_unit : Optional[str] = None
    i_avg_ope : Optional[str] = None
    i_avg_ope_unit : Optional[str] = None
    v_avg_ope : Optional[str] = None
    v_avg_ope_unit : Optional[str] = None
    motor_power : Optional[str] = None
    motor_power_unit : Optional[str] = None
    shaft_ope : Optional[str] = None
    shaft_ope_unit : Optional[str] = None
    head_ope : Optional[str] = None
    head_ope_unit : Optional[str] = None
    head_shut : Optional[str] = None
    head_shut_unit : Optional[str] = None
    head_max : Optional[str] = None
    head_max_unit : Optional[str] = None
    env_temp : Optional[str] = None
    env_temp_unit : Optional[str] = None
    liquid_temp : Optional[str] = None
    liquid_temp_unit : Optional[str] = None
    npsha : Optional[str] = None
    npsha_unit : Optional[str] = None
    npsha_actual : Optional[str] = None
    npsha_actual_unit : Optional[str] = None
    suction_fluid_velo : Optional[str] = None
    suction_fluid_velo_unit : Optional[str] = None
    discharge_fluid_velo : Optional[str] = None
    discharge_fluid_velo_unit : Optional[str] = None
    remarks : Optional[str] = None

    v_pump_de_h : Optional[str] = None
    v_pump_de_h_unit : Optional[str] = None
    v_pump_de_v : Optional[str] = None
    v_pump_de_v_unit : Optional[str] = None
    v_pump_de_a : Optional[str] = None
    v_pump_de_a_unit : Optional[str] = None
    v_pump_nde_h : Optional[str] = None
    v_pump_nde_h_unit : Optional[str] = None
    v_pump_nde_v : Optional[str] = None
    v_pump_nde_v_unit : Optional[str] = None
    v_pump_nde_a : Optional[str] = None
    v_pump_nde_a_unit : Optional[str] = None
    v_motor_de_h : Optional[str] = None
    v_motor_de_h_unit : Optional[str] = None
    v_motor_de_v : Optional[str] = None
    v_motor_de_v_unit : Optional[str] = None
    v_motor_de_a : Optional[str] = None
    v_motor_de_a_unit : Optional[str] = None
    v_motor_nde_h : Optional[str] = None
    v_motor_nde_h_unit : Optional[str] = None
    v_motor_nde_v : Optional[str] = None
    v_motor_nde_v_unit : Optional[str] = None
    v_motor_nde_a : Optional[str] = None
    v_motor_nde_a_unit : Optional[str] = None
    a_pump_de_h : Optional[str] = None
    a_pump_de_h_unit : Optional[str] = None
    a_pump_de_v : Optional[str] = None
    a_pump_de_v_unit : Optional[str] = None
    a_pump_de_a : Optional[str] = None
    a_pump_de_a_unit : Optional[str] = None
    a_pump_nde_h : Optional[str] = None
    a_pump_nde_h_unit : Optional[str] = None
    a_pump_nde_v : Optional[str] = None
    a_pump_nde_v_unit : Optional[str] = None
    a_pump_nde_a : Optional[str] = None
    a_pump_nde_a_unit : Optional[str] = None
    a_motor_de_h : Optional[str] = None
    a_motor_de_h_unit : Optional[str] = None
    a_motor_de_v : Optional[str] = None
    a_motor_de_v_unit : Optional[str] = None
    a_motor_de_a : Optional[str] = None
    a_motor_de_a_unit : Optional[str] = None
    a_motor_nde_h : Optional[str] = None
    a_motor_nde_h_unit : Optional[str] = None
    a_motor_nde_v : Optional[str] = None
    a_motor_nde_v_unit : Optional[str] = None
    a_motor_nde_a : Optional[str] = None
    a_motor_nde_a_unit : Optional[str] = None
    temp_pump_nde : Optional[str] = None
    temp_pump_nde_unit : Optional[str] = None
    temp_pump_de : Optional[str] = None
    temp_pump_de_unit : Optional[str] = None
    temp_motor_nde : Optional[str] = None
    temp_motor_nde_unit : Optional[str] = None
    temp_motor_de : Optional[str] = None
    temp_motor_de_unit : Optional[str] = None
    env_vibration : Optional[str] = None
    env_vibration_unit : Optional[str] = None

    alignment_check : Optional[str] = None
    coupling_check : Optional[str] = None
    suction_valve_check : Optional[str] = None
    rotate_hand_check : Optional[str] = None
    axial_hand_check : Optional[str] = None
    gap_check : Optional[str] = None
    discharge_valve_check : Optional[str] = None
    bolt_check : Optional[str] = None
    oil_grease_check : Optional[str] = None
    electricity_check : Optional[str] = None
    service_check : Optional[str] = None
    leakage_check : Optional[str] = None
    corrosion_check : Optional[str] = None
    painting_check : Optional[str] = None
    noise_check : Optional[str] = None
    noise_run_check : Optional[str] = None
    oil_grease_run_check : Optional[str] = None
    leakage_run_check : Optional[str] = None
    mechanical_run_check : Optional[str] = None
    cavitation_run_check : Optional[str] = None
    corrosion_run_check : Optional[str] = None
    suction_valve_run_check : Optional[str] = None
    discharge_valve_run_check : Optional[str] = None
    painting_run_check : Optional[str] = None
    electric_connectivity_run_check : Optional[str] = None
    service_piping_run_check : Optional[str] = None
    bolt_nut_run_check : Optional[str] = None
    barrier_fluid_run_pres_check : Optional[str] = None
    remarks_check : Optional[str] = None
    alignment_remark : Optional[str] = None
    coupling_remark : Optional[str] = None
    suction_valve_remark : Optional[str] = None
    rotating_remark : Optional[str] = None
    axial_hand_remark : Optional[str] = None
    gap_remark : Optional[str] = None
    discharge_valve_remark : Optional[str] = None
    bolt_remark : Optional[str] = None
    oil_remark : Optional[str] = None
    electricity_remark : Optional[str] = None
    service_remark : Optional[str] = None
    leakage_remark : Optional[str] = None
    corrosion_remark : Optional[str] = None
    painting_remark : Optional[str] = None
    noise_remark : Optional[str] = None
    noise_run_remark : Optional[str] = None
    oil_run_remark : Optional[str] = None
    leakage_run_remark : Optional[str] = None
    mechanical_run_remark : Optional[str] = None
    cavitation_run_remark : Optional[str] = None
    corrosion_run_remark : Optional[str] = None
    suction_valve_run_remark : Optional[str] = None
    discharge_valve_run_remark : Optional[str] = None
    painting_run_remark : Optional[str] = None
    electric_connectivity_run_remark : Optional[str] = None
    service_piping_run_remark : Optional[str] = None
    bolt_nut_run_remark : Optional[str] = None
    barrier_fluid_run_pres_remark : Optional[str] = None

class EngineerReportCheckPayload_schema(Schema):
    cal_check : Optional[EngineerReportCheckCal_schema] = None
    vibration_check : Optional[EngineerReportCheckVibe_schema] = None
    visual_check : Optional[EngineerReportCheckVisual_schema] = None
    result_check : Optional[EngineerReportCheckResult_schema] = None
    
class EngineerReportData_schema(Schema):
    data_cal : Optional[EngineerReportCheckCal_schema] = None
    data_vibe : Optional[EngineerReportCheckVibe_schema] = None
    data_visual : Optional[EngineerReportCheckVisual_schema] = None
    data_result : Optional[EngineerReportCheckResult_schema] = None
    pump_data : Optional[PumpDetail_schema] = None
    user_data : Optional[str] = None