# Generated by Django 5.0.6 on 2024-07-07 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pumps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BearingList",
            fields=[
                ("rotation_de_id", models.AutoField(primary_key=True, serialize=False)),
                ("rotation", models.TextField()),
            ],
            options={
                "db_table": "tbl_bearing_lov",
            },
        ),
        migrations.CreateModel(
            name="CasingMaterialList",
            fields=[
                ("mat_cover_id", models.AutoField(primary_key=True, serialize=False)),
                ("mat_cover_name", models.TextField()),
                ("mat_cover_type", models.TextField()),
            ],
            options={
                "db_table": "tbl_cover_mat_lov",
            },
        ),
        migrations.CreateModel(
            name="FaceMaterialDetail",
            fields=[
                ("mat_face_id", models.AutoField(primary_key=True, serialize=False)),
                ("mat_face_name", models.TextField()),
                ("mat_face_type", models.TextField()),
            ],
            options={
                "db_table": "tbl_face_mat_lov",
            },
        ),
        migrations.CreateModel(
            name="FlangRatingList",
            fields=[
                (
                    "flang_rating_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("flang_rating_name", models.TextField()),
            ],
            options={
                "db_table": "tbl_flang_rating_lov",
            },
        ),
        migrations.CreateModel(
            name="ImpellerList",
            fields=[
                (
                    "lmpeller_type_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("lmpeller_type_name", models.TextField()),
            ],
            options={
                "db_table": "tbl_impeller_type_lov",
            },
        ),
        migrations.CreateModel(
            name="MechanicalDesignList",
            fields=[
                ("mech_design_id", models.AutoField(primary_key=True, serialize=False)),
                ("mech_design_name", models.TextField()),
            ],
            options={
                "db_table": "tbl_mech_design_lov",
            },
        ),
        migrations.CreateModel(
            name="MechSealApiPlanList",
            fields=[
                (
                    "mech_api_plan",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "tbl_api_lov",
            },
        ),
        migrations.CreateModel(
            name="MotorDetailList",
            fields=[
                ("motor_drive_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "drive_system",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("ie_class", models.CharField(blank=True, max_length=30, null=True)),
                ("standard", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                "db_table": "tbl_motor_detail_lov",
            },
        ),
        migrations.CreateModel(
            name="PumpDetailList",
            fields=[
                ("pump_id", models.AutoField(primary_key=True, serialize=False)),
                ("pump_design", models.TextField()),
                ("pump_type", models.TextField()),
            ],
            options={
                "db_table": "tbl_pump_detail_lov",
            },
        ),
        migrations.CreateModel(
            name="PumpStandardList",
            fields=[
                (
                    "pump_standard_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "tbl_pump_standard_lov",
            },
        ),
        migrations.CreateModel(
            name="SpringMaterialDetail",
            fields=[
                ("mat_spring_id", models.AutoField(primary_key=True, serialize=False)),
                ("mat_spring_name", models.TextField()),
                ("mat_spring_type", models.TextField()),
            ],
            options={
                "db_table": "tbl_spring_mat_lov",
            },
        ),
        migrations.CreateModel(
            name="SuctionPipeInfoList",
            fields=[
                ("pipe_lov_id", models.AutoField(primary_key=True, serialize=False)),
                ("pipe_sch", models.TextField()),
                ("pipe_size", models.TextField()),
                ("pipe_id", models.TextField()),
                ("fac_number", models.CharField(max_length=20)),
                ("equipment", models.CharField(max_length=50)),
                ("brand", models.CharField(max_length=50)),
                ("model_short", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("data_type", models.CharField(max_length=10)),
                ("sequence", models.IntegerField()),
                ("rpm", models.IntegerField()),
                ("imp_dia", models.DecimalField(decimal_places=0, max_digits=10)),
                ("flow", models.DecimalField(decimal_places=0, max_digits=15)),
                ("head", models.DecimalField(decimal_places=0, max_digits=15)),
                ("eff", models.IntegerField()),
                ("npshr", models.DecimalField(decimal_places=0, max_digits=15)),
                ("kw", models.DecimalField(decimal_places=0, max_digits=15)),
                ("curve_format", models.CharField(max_length=20)),
                ("eff_rl", models.CharField(max_length=10)),
                ("eff_status", models.IntegerField()),
                ("eff_distance", models.DecimalField(decimal_places=0, max_digits=15)),
                ("tolerance", models.IntegerField()),
                ("scale_xy", models.DecimalField(decimal_places=0, max_digits=15)),
                ("update_time", models.DateTimeField()),
                ("dry_sat", models.CharField(max_length=10)),
                ("liquid", models.DecimalField(decimal_places=0, max_digits=15)),
            ],
            options={
                "db_table": "tbl_pipe_sch_lov",
            },
        ),
        migrations.CreateModel(
            name="TblSuctionDischargeLov",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("suction_discharge_value", models.TextField()),
            ],
            options={
                "db_table": "tbl_suction_discharge_lov",
            },
        ),
        migrations.CreateModel(
            name="UnitList",
            fields=[
                ("k_lov_id", models.AutoField(primary_key=True, serialize=False)),
                ("field_id", models.CharField(max_length=50)),
                ("field_value", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "tbl_k_monitoring_lov",
            },
        ),
        migrations.CreateModel(
            name="VibrationDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voltage", models.CharField(blank=True, max_length=30, null=True)),
                ("acceptable", models.CharField(blank=True, max_length=10, null=True)),
                ("unsatisfied", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "unacceptable",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "tbl_vibration_lov",
            },
        ),
        migrations.RemoveField(
            model_name="pumpdetail",
            name="impeller_type",
        ),
        migrations.AlterField(
            model_name="pumpdetail",
            name="impeller_type_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pumps.impellerlist",
            ),
        ),
    ]
