# Generated by Django 5.0.6 on 2024-07-08 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pumps", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pumpdetail",
            options={"verbose_name": "PUMP", "verbose_name_plural": "PUMPS"},
        ),
        migrations.AlterField(
            model_name="pumpdetail",
            name="coup_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coup_type",
                to="pumps.unitlist",
            ),
        ),
        migrations.AlterField(
            model_name="pumpdetail",
            name="doc_no",
            field=models.TextField(unique=True),
        ),
    ]
