# Generated by Django 5.0.6 on 2024-07-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pumps", "0002_alter_pumpdetail_options_alter_pumpdetail_coup_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pumpdetail",
            name="doc_no",
            field=models.TextField(max_length=500, unique=True),
        ),
    ]
