# Generated by Django 5.0.6 on 2024-07-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pumps", "0003_alter_engineeringdetail_user_alter_pumpdetail_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pumpdetail",
            name="timestamp",
            field=models.DateTimeField(editable=False),
        ),
    ]
