# Generated by Django 5.0.6 on 2024-07-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pumps", "0003_alter_pumpdetail_doc_no"),
    ]

    operations = [
        migrations.RenameField(
            model_name="impellerlist",
            old_name="lmpeller_type_id",
            new_name="impeller_type_id",
        ),
        migrations.RenameField(
            model_name="impellerlist",
            old_name="lmpeller_type_name",
            new_name="impeller_type_name",
        ),
    ]
