# Generated by Django 5.0.6 on 2024-07-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pumps", "0004_alter_pumpdetail_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pumpdetail",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
