# Generated by Django 5.0.6 on 2024-07-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pumps",
            "0004_rename_lmpeller_type_id_impellerlist_impeller_type_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pumpdetail",
            name="bep_flow",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="pumpdetail",
            name="design_flow",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="pumpdetail",
            name="design_head",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="pumpdetail",
            name="discharge_velo",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="pumpdetail",
            name="max_head",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="pumpdetail",
            name="min_head",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="pumpdetail",
            name="npshr",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="pumpdetail",
            name="pump_efficiency",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="pumpdetail",
            name="suction_velo",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="pumpdetail",
            name="voltage",
            field=models.FloatField(),
        ),
    ]
