# Generated by Django 5.0.6 on 2024-07-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pumps", "0005_alter_pumpdetail_bep_flow_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pumpdetail",
            name="design_temp",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="pumpdetail",
            name="max_temp",
            field=models.FloatField(),
        ),
    ]
