# Generated by Django 5.0.6 on 2024-07-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pumps", "0007_factorytable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factorytable",
            name="data_type",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="factorytable",
            name="eff",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="factorytable",
            name="equipment",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="factorytable",
            name="fac_number",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="factorytable",
            name="flow",
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="factorytable",
            name="head",
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="factorytable",
            name="imp_dia",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="factorytable",
            name="kw",
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="factorytable",
            name="model",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="factorytable",
            name="npshr",
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
    ]
