# Generated by Django 5.0.6 on 2024-07-30 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pumps", "0008_alter_factorytable_data_type_alter_factorytable_eff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engineeringdetail",
            name="pump_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="engineering_details",
                to="pumps.pumpdetail",
            ),
        ),
    ]
