services:
  frontend:
    build:
      context: ./frontend
    container_name: kmonitor_frontend
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:80"

  backend:
    volumes:
      - /var/www/myproject/storage:/var/www/myproject/storage
    build:
      context: ./backend
    container_name: kmonitor_backend
    restart: unless-stopped
    network_mode: host
    env_file:
      - ./backend/.env