version: "3.9"

services:

  backend:
    build: ./backend
    container_name: kmonitor_backend
    restart: always
    ports:
      - "127.0.0.1:8000:8000"

  frontend:
    build: ./frontend
    container_name: kmonitor_frontend
    restart: always
    ports:
      - "127.0.0.1:3000:80"