# Generated by Django 5.1.3 on 2024-12-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='list_of_values',
            fields=[
                ('list_of_value_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('list_of_value_type', models.CharField(max_length=100)),
                ('list_of_value_name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
    ]
