# Generated by Django 5.1.3 on 2024-12-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pump_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='list_of_values',
            new_name='ListOfValue',
        ),
    ]
