# Generated by Django 5.1.5 on 2025-02-21 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pump_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pumpdetaillov',
            table=None,
        ),
    ]
