# Generated by Django 5.1.3 on 2024-12-04 07:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump_data', '0002_rename_list_of_values_listofvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='KMonitoringLOV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('data_value', models.CharField(blank=True, max_length=100, null=True)),
                ('data_value2', models.CharField(blank=True, max_length=100, null=True)),
                ('data_value3', models.CharField(blank=True, max_length=100, null=True)),
                ('data_value4', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ListOfValue',
        ),
    ]
