# Generated by Django 5.1.5 on 2025-02-21 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pump_data', '0002_alter_pumpdetaillov_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pumpdetaillov',
            table='tbl_pump_detail_lov',
        ),
    ]
