# Generated by Django 5.1.5 on 2025-02-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump_data', '0003_alter_pumpdetaillov_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumpdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
