# Generated by Django 5.1.3 on 2024-12-13 04:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump_data', '0004_motordetaillov_pumpdetaillov_pumpstandardlov_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PumpDetail',
            fields=[
                ('pump_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_customer', models.CharField(max_length=100)),
                ('doc_no', models.CharField(max_length=100)),
                ('doc_date', models.CharField(max_length=100)),
            ],
        ),
    ]
