# Generated by Django 5.1.5 on 2025-03-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump_data', '0004_pumpdetail_created_at_pumpdetail_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumpdetaillov',
            name='pump_code_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
