# Generated by Django 5.1.5 on 2025-03-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump_data', '0005_pumpdetaillov_pump_code_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='motordetaillov',
            name='motor_code_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpmateriallov',
            name='mat_code_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shaftseallov',
            name='shaft_seal_code_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
