# Generated by Django 5.1.3 on 2025-01-14 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump_data', '0005_pumpdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pumpdetail',
            name='doc_customer',
        ),
        migrations.RemoveField(
            model_name='pumpdetail',
            name='doc_date',
        ),
        migrations.RemoveField(
            model_name='pumpdetail',
            name='doc_no',
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='brand',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='location',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='model',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_design',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_standard',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_standard_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pump_standard_id', to='pump_data.pumpdetaillov'),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pump_type_id', to='pump_data.pumpdetaillov'),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_type_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='serial_no',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='stage',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='tag_no',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
