# Generated by Django 5.1.5 on 2025-01-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump_data', '0006_remove_pumpdetail_doc_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='location',
            new_name='company_code',
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='design_flow',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='design_flow_unit',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='design_head',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='design_head_unit',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='min_head',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='min_head_unit',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='motor_brand',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='motor_connection',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='motor_drive',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='motor_efficiency',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='motor_efficiency_unit',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='motor_factor',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='motor_frame',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='motor_ie',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='motor_model',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='motor_phase',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='motor_protection',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='motor_rate',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='motor_rate_unit',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='motor_serial_no',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='motor_speed',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='motor_speed_unit',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='motor_standard',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='npshr',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='npshr_unit',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='power_required_cal',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='power_required_cal_unit',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_efficiency',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_efficiency_unit',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_lining_mat',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_speed',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_speed_unit',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_standard_no',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='voltage',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='voltage_unit',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
