# Generated by Django 5.1.5 on 2025-05-09 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump_data', '0006_motordetaillov_motor_code_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaLOV',
            fields=[
                ('media_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_name', models.TextField(blank=True, max_length=100, null=True)),
                ('media_density', models.TextField(blank=True, max_length=100, null=True)),
                ('media_viscosity', models.TextField(blank=True, max_length=100, null=True)),
                ('media_concentration_percentage', models.TextField(blank=True, max_length=100, null=True)),
                ('operating_temperature', models.TextField(blank=True, max_length=100, null=True)),
                ('vapor_pressure', models.TextField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_media_lov',
            },
        ),
    ]
