# Generated by Django 5.1.5 on 2025-05-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump_data', '0007_medialov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medialov',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medialov',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
