# Generated by Django 5.1.5 on 2025-05-16 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pump_data', '0008_alter_medialov_created_at_alter_medialov_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pumpdetaillov',
            name='pump_discharge_rating_id',
        ),
        migrations.RemoveField(
            model_name='pumpdetaillov',
            name='pump_suction_rating_id',
        ),
    ]
