# Generated by Django 5.1.5 on 2025-05-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump_data', '0009_remove_pumpdetaillov_pump_discharge_rating_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medialov',
            name='media_density_unit',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medialov',
            name='media_viscosity_unit',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medialov',
            name='vapor_pressure_unit',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
