# Generated by Django 5.1.5 on 2025-05-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump_data', '0010_medialov_media_density_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motordetaillov',
            name='coup_type',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
