# Generated by Django 5.1.5 on 2025-05-30 09:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump_data', '0011_motordetaillov_coup_type'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='base_plate_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='bearing_de_one',
            new_name='casing_cover_mat',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='bearing_de_one_id',
            new_name='casing_mat',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='bearing_de_two',
            new_name='diffuser_mat',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='bearing_de_two_id',
            new_name='discharge_head',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='bearing_lubric_brand',
            new_name='discharge_pipe_length_h_unit',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='bearing_lubric_no',
            new_name='discharge_pipe_length_v_unit',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='bearing_lubric_type',
            new_name='impeller_mat',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='bearing_nde_one',
            new_name='impeller_type',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='bearing_nde_one_id',
            new_name='mat_code_name',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='pump_mat_id',
            new_name='mat_lov_id',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='bearing_nde_two',
            new_name='mech_main_pre_unit',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='bearing_nde_two_id',
            new_name='mechanical_seal_api_plan',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='discharge_pipe_data_id',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='mech_api_plan',
            new_name='model_short',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='pump_discharge_rating_id',
            new_name='motor_brand',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='pump_discharge_size_id',
            new_name='motor_code_name',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='pump_suction_rating_id',
            new_name='motor_connection',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='pump_suction_size_id',
            new_name='motor_drive',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='rotation_de',
            new_name='motor_efficiency',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='solid_type_id',
            new_name='motor_efficiency_unit',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='suction_pipe_data_id',
            new_name='motor_factor',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='suggest_motor',
            new_name='motor_ie',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='motor_detail_id',
            new_name='motor_lov_id',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='voltage',
            new_name='motor_model',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='voltage_unit',
            new_name='motor_phase',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='pump_model_id',
            new_name='pump_lov_id',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='shaft_seal_id',
            new_name='shaft_seal_lov_id',
        ),
        migrations.RemoveField(
            model_name='pumpdetail',
            name='bearing_last_chg_dt',
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.companiesdetail'),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='media_lov_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pump_data.medialov'),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='motor_rated',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='motor_rated_current',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='motor_rated_current_unit',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='motor_rated_unit',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='motor_serial_no',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='motor_speed',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='motor_speed_unit',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='motor_standard',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='operating_flow',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='operating_flow_unit',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='operating_head',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='operating_head_unit',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_base_mat',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_code_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_head_cover_mat',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_head_mat',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_lining_mat',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_model_size',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_type_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='serial_no',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='shaft_seal_brand',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='shaft_seal_code_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='shaft_seal_design',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='shaft_seal_material',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='shaft_seal_model',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='stage',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='suction_head_unit',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='suction_pipe_length_unit',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pumpdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pumpdetail',
            name='doc_date',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pumpdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
