# Generated by Django 5.1.5 on 2025-06-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump_data', '0012_rename_base_plate_id_pumpdetail_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumpdetail',
            name='bearing_de_one',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='bearing_de_two',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='bearing_last_chg_dt',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='bearing_lubric_brand',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='bearing_lubric_no',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='bearing_lubric_type',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='bearing_nde_one',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='bearing_nde_two',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='oil_seal',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='rotation_de',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
