# Generated by Django 5.1.5 on 2025-06-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pump_data', '0013_pumpdetail_bearing_de_one_pumpdetail_bearing_de_two_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motordetaillov',
            old_name='motor_id',
            new_name='motor_lov_id',
        ),
    ]
