# Generated by Django 5.1.5 on 2025-06-02 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pump_data', '0014_rename_motor_id_motordetaillov_motor_lov_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shaftseallov',
            old_name='shaft_seal_id',
            new_name='shaft_seal_lov_id',
        ),
    ]
