# Generated by Django 5.1.5 on 2025-06-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump_data', '0015_rename_shaft_seal_id_shaftseallov_shaft_seal_lov_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumpdetail',
            name='company_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pumpdetail',
            name='mat_lov_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pumpdetail',
            name='media_lov_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pumpdetail',
            name='motor_lov_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pumpdetail',
            name='pump_lov_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pumpdetail',
            name='shaft_seal_lov_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
