# Generated by Django 5.1.5 on 2025-06-11 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump_data', '0016_alter_pumpdetail_company_id_and_more'),
        ('users', '0003_alter_companiesdetail_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pumpdetail',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='pumpdetail',
            name='mat_lov_id',
        ),
        migrations.RemoveField(
            model_name='pumpdetail',
            name='media_lov_id',
        ),
        migrations.RemoveField(
            model_name='pumpdetail',
            name='motor_lov_id',
        ),
        migrations.RemoveField(
            model_name='pumpdetail',
            name='pump_lov_id',
        ),
        migrations.RemoveField(
            model_name='pumpdetail',
            name='shaft_seal_lov_id',
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.companiesdetail'),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='mat_lov',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pump_data.pumpmateriallov'),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='media_lov',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pump_data.medialov'),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='motor_lov',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pump_data.motordetaillov'),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_lov',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pump_data.pumpdetaillov'),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='shaft_seal_lov',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pump_data.shaftseallov'),
        ),
    ]
