# Generated by Django 5.1.5 on 2025-06-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump_data', '0017_remove_pumpdetail_company_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='company',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='mat_lov',
            new_name='mat_lov_id',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='media_lov',
            new_name='media_lov_id',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='motor_lov',
            new_name='motor_lov_id',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='pump_lov',
            new_name='pump_lov_id',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='shaft_seal_lov',
            new_name='shaft_seal_lov_id',
        ),
        migrations.RenameField(
            model_name='pumpdetaillov',
            old_name='model_size',
            new_name='pump_impeller_max_size',
        ),
        migrations.RenameField(
            model_name='pumpdetaillov',
            old_name='pump_type',
            new_name='pump_model_size',
        ),
        migrations.AddField(
            model_name='pumpdetaillov',
            name='pump_type_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
