# Generated by Django 5.1.5 on 2025-06-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump_data', '0018_rename_company_pumpdetail_company_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medialov',
            old_name='media_id',
            new_name='media_lov_id',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='concentration',
            new_name='liner_mat',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='density',
            new_name='media_concentration_percentage',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='diffuser_mat',
            new_name='media_density',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='media',
            new_name='media_density_unit',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='density_unit',
            new_name='media_name',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='oper_temp',
            new_name='media_viscosity',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='pump_lining_mat',
            new_name='media_viscosity_unit',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='viscosity',
            new_name='operating_temperature',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='viscosity_unit',
            new_name='pump_mat_code',
        ),
        migrations.RenameField(
            model_name='pumpmateriallov',
            old_name='material_id',
            new_name='mat_lov_id',
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_type_mat',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='stage_casing_diffuser_mat',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
