# Generated by Django 5.1.5 on 2025-06-18 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pump_data', '0019_rename_media_id_medialov_media_lov_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pumpmateriallov',
            old_name='base_mat',
            new_name='pump_base_mat',
        ),
    ]
