# Generated by Django 5.1.5 on 2025-06-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump_data', '0020_rename_base_mat_pumpmateriallov_pump_base_mat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='brand',
            new_name='address_en',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='impeller_max',
            new_name='address_th',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='impeller_type',
            new_name='base_plate_id',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='model',
            new_name='company_name_en',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='model_short',
            new_name='company_name_th',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='operating_flow',
            new_name='customer_industry_group',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='operating_flow_unit',
            new_name='map',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='operating_head',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='operating_head_unit',
            new_name='pump_brand',
        ),
        migrations.RenameField(
            model_name='pumpdetail',
            old_name='stage',
            new_name='pump_discharge_size_id',
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_flange_con_std',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_impeller_max_size',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_impeller_type',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_max_temp',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_model',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_oil_seal',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_seal_chamber',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_stage',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='pump_suction_size_id',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='sales_area',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='seal_cham',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='suggest_motor',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='voltage',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pumpdetail',
            name='voltage_unit',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
