import { z } from "zod";
export const PumpDetailFormSchema = z.object({

  company_code : z.string().optional() ,
  doc_customer : z.string().optional(),
  doc_no : z.string().optional(),
  doc_date : z.string().optional(),
  tag_no : z.string().optional(),
  pump_lov_id : z.string().optional(),
  pump_standard : z.string().optional(),
  pump_standard_no : z.string().optional(),
  pump_design : z.string().optional(),
  location : z.string().optional(),
  base_plate : z.string().optional(),
  pump_status : z.string().optional(),
/* Pump Technical details */
  max_temp : z.string().optional(),
  max_flow : z.string().optional(),
  max_flow_unit : z.string().optional(),
  min_flow : z.string().optional(),
  min_flow_unit : z.string().optional(),
  pump_speed : z.string().optional(),
  pump_speed_unit : z.string().optional(),
  design_flow : z.string().optional(),
  design_flow_unit : z.string().optional(),
  design_head : z.string().optional(),
  design_head_unit : z.string().optional(),
  shut_off_head : z.string().optional(),
  shut_off_head_unit : z.string().optional(),
  min_head : z.string().optional(),
  min_head_unit : z.string().optional(),
  max_head : z.string().optional(),
  max_head_unit : z.string().optional(),
  suction_velo : z.string().optional(),
  suction_velo_unit : z.string().optional(),
  discharge_velo : z.string().optional(),
  discharge_velo_unit : z.string().optional(),
  bep_head : z.string().optional(),
  bep_head_unit : z.string().optional(),
  bep_flow : z.string().optional(),
  bep_flow_unit : z.string().optional(),
  npshr : z.string().optional(),
  npshr_unit : z.string().optional(),
  pump_efficiency : z.string().optional(),
  pump_efficiency_unit : z.string().optional(),
  hyd_power : z.string().optional(),
  hyd_power_unit : z.string().optional(),
  power_required_cal : z.string().optional(),
  power_required_cal_unit : z.string().optional(),
  power_min_flow : z.string().optional(),
  power_min_flow_unit : z.string().optional(),
  power_max_flow : z.string().optional(),
  power_max_flow_unit : z.string().optional(),
  power_bep_flow : z.string().optional(),
  power_bep_flow_unit : z.string().optional(),
/* Pump Application Data */
  media : z.string().optional(),
  oper_temp : z.string().optional(),
  solid_type : z.string().optional(),
  solid_diameter : z.string().optional(),
  density : z.string().optional(),
  density_unit : z.string().optional(),
  viscosity : z.string().optional(),
  viscosity_unit : z.string().optional(),
  vapor_pressure : z.string().optional(),
  vapor_pressure_unit : z.string().optional(),
  tank_position : z.string().optional(),
  tank_design : z.string().optional(),
  tank_pressure : z.string().optional(),
  suction_head : z.string().optional(),
  concentration : z.string().optional(),
solid_percentage : z.string().optional(),
})

export const MotorAndCouplingDetailFormSchema = z.object({
  /* Coupling Details */
coup_type : z.string().optional(),
  /* Motor General Details */
  motor_lov_id : z.string().optional(),
  motor_model : z.string().optional(),
  motor_serial_no : z.string().optional(),
  motor_brand : z.string().optional(),
  motor_drive : z.string().optional(),
  motor_standard : z.string().optional(),
  motor_ie : z.string().optional(),
  motor_speed : z.string().optional(),
  motor_speed_unit : z.string().optional(),
  motor_rated : z.string().optional(),
  motor_rated_unit : z.string().optional(),
  motor_factor : z.string().optional(),
  motor_connection : z.string().optional(),
  motor_phase : z.string().optional(),
  motor_efficiency : z.string().optional(),
  motor_efficiency_unit : z.string().optional(),
  motor_rated_current : z.string().optional(),
  motor_rated_current_unit : z.string().optional(),
})

export const MaterialAndImpellerDetailFormSchema = z.object({
  /* Material and Impeller Details */
  pump_mat_id : z.string().optional(),
  casing_mat : z.string().optional(),
  casing_cover_mat : z.string().optional(),
  diffuser_mat : z.string().optional(),
  pump_base_mat : z.string().optional(),
  pump_head_mat : z.string().optional(),
  pump_head_cover_mat : z.string().optional(),
  design_impeller_dia : z.string().optional(),
  impeller_max : z.string().optional(),
  impeller_type : z.string().optional(),
  impeller_mat : z.string().optional(),
  pump_lining_mat : z.string().optional(),
})

export const MechanicalSealDetailFormSchema = z.object({
  /* Mechanical Seal Details */
  mech_api_plan : z.string().optional(),
  mech_main_temp : z.string().optional(),
  mech_main_pre : z.string().optional(),
  mech_size : z.string().optional(),
  mech_size_unit : z.string().optional(),
  seal_cham : z.string().optional(),
  shaft_seal_brand : z.string().optional(),
  shaft_seal_design_id : z.string().optional(),
shaft_seal_design : z.string().optional(),
  shaft_seal_mat : z.string().optional(),
})
export const FlangeAndBearingDetailFormSchema = z.object({
  /* Bearing Detail */
bearing_nde_one_id : z.string().optional(),
bearing_nde_one : z.string().optional(),
bearing_nde_two_id : z.string().optional(),
bearing_nde_two : z.string().optional(),
  bearing_lubric_type : z.string().optional(),
  bearing_lubric_brand : z.string().optional(),
  bearing_lubric_no : z.string().optional(),
  rotation_de : z.string().optional(),
bearing_de_one_id : z.string().optional(),
bearing_de_one : z.string().optional(),
bearing_de_two_id : z.string().optional(),
bearing_de_two : z.string().optional(),
bearing_last_chg_dt : z.string().optional(),
  /* Flange Details */
flang_con_std : z.string().optional(),
  pump_suction_size_id : z.string().optional(),
  pump_suction_size_id_unit : z.string().optional(),
  pump_suction_rating: z.string().optional(),
  pump_discharge_size_id : z.string().optional(),
  pump_discharge_size_id_unit : z.string().optional(),
  pump_discharge_rating : z.string().optional(),
suction_pipe_data_id : z.string().optional(),
  suction_pipe_size : z.string().optional(),
  suction_pipe_sch : z.string().optional(),
discharge_pipe_data_id : z.string().optional(),
  discharge_pipe_size : z.string().optional(),
  discharge_pipe_sch : z.string().optional(),
  suction_pipe_length : z.string().optional(),
  discharge_pipe_length_h : z.string().optional(),
  discharge_pipe_length_v : z.string().optional(),
  suction_pipe_id : z.string().optional(),
  suction_pipe_id_unit : z.string().optional(),
  discharge_pipe_id : z.string().optional(),
  discharge_pipe_id_unit : z.string().optional(),
  suction_elbow : z.string().optional(),
  suction_tee : z.string().optional(),
  suction_reducer : z.string().optional(),
  suction_valve : z.string().optional(),
  suction_y_strainer : z.string().optional(),
  suction_other : z.string().optional(),
  suction_equi_length : z.string().optional(),
  discharge_equi_length : z.string().optional(),
  discharge_elbow : z.string().optional(),
  discharge_tee : z.string().optional(),
  discharge_reducer : z.string().optional(),
  discharge_valve : z.string().optional(),
  discharge_y_strainer : z.string().optional(),
  discharge_other : z.string().optional(),
})


export const PumpDetailSchema = z.object({
  /* Related tables */
  pump_model_id : z.string().optional(),
  pump_mat_id : z.string().optional(),
  motor_detail_id : z.string().optional(),
  shaft_seal_id : z.string().optional(),
  /* Pump General details */
  company_code : z.string().optional(),
  doc_customer : z.string().optional(),
  doc_no : z.string().optional(),
  doc_date : z.string().optional(),
  tag_no : z.string().optional(),
  pump_standard : z.string().optional(),
  pump_standard_no : z.string().optional(),
  pump_design : z.string().optional(),
  location : z.string().optional(),
  base_plate_id : z.string().optional(),
  base_plate : z.string().optional(),
  pump_status : z.string().optional(),
  /* Pump Technical details */
  max_temp : z.string().optional(),
  max_flow : z.string().optional(),
  max_flow_unit : z.string().optional(),
  min_flow : z.string().optional(),
  min_flow_unit : z.string().optional(),
  pump_speed : z.string().optional(),
  pump_speed_unit : z.string().optional(),
  design_flow : z.string().optional(),
  design_flow_unit : z.string().optional(),
  design_head : z.string().optional(),
  design_head_unit : z.string().optional(),
  shut_off_head : z.string().optional(),
  shut_off_head_unit : z.string().optional(),
  min_head : z.string().optional(),
  min_head_unit : z.string().optional(),
  max_head : z.string().optional(),
  max_head_unit : z.string().optional(),
  suction_velo : z.string().optional(),
  suction_velo_unit : z.string().optional(),
  discharge_velo : z.string().optional(),
  discharge_velo_unit : z.string().optional(),
  bep_head : z.string().optional(),
  bep_head_unit : z.string().optional(),
  bep_flow : z.string().optional(),
  bep_flow_unit : z.string().optional(),
  npshr : z.string().optional(),
  npshr_unit : z.string().optional(),
  pump_efficiency : z.string().optional(),
  pump_efficiency_unit : z.string().optional(),
  hyd_power : z.string().optional(),
  hyd_power_unit : z.string().optional(),
  power_required_cal : z.string().optional(),
  power_required_cal_unit : z.string().optional(),
  power_min_flow : z.string().optional(),
  power_min_flow_unit : z.string().optional(),
  power_max_flow : z.string().optional(),
  power_max_flow_unit : z.string().optional(),
  power_bep_flow : z.string().optional(),
  power_bep_flow_unit : z.string().optional(),
  /* Pump Application Data */
  media : z.string().optional(),
  oper_temp : z.string().optional(),
  solid_type_id : z.string().optional(),
  solid_type : z.string().optional(),
  solid_diameter : z.string().optional(),
  density : z.string().optional(),
  density_unit : z.string().optional(),
  viscosity : z.string().optional(),
  viscosity_unit : z.string().optional(),
  vapor_pressure : z.string().optional(),
  vapor_pressure_unit : z.string().optional(),
  tank_position : z.string().optional(),
  tank_design : z.string().optional(),
  tank_pressure : z.string().optional(),
  suction_head : z.string().optional(),
  concentration : z.string().optional(),
  solid_percentage : z.string().optional(),
  /* Motor General Details */
  voltage : z.string().optional(),
  voltage_unit : z.string().optional(),
  suggest_motor : z.string().optional(),
  /* Mechanical Seal Details */
  mech_api_plan : z.string().optional(),
  mech_main_temp : z.string().optional(),
  mech_main_pre : z.string().optional(),
  mech_size : z.string().optional(),
  mech_size_unit : z.string().optional(),
  /* Material and Impeller Details */
  design_impeller_dia : z.string().optional(),
  impeller_max : z.string().optional(),
  /* Flange Details */
  flang_con_std : z.string().optional(),
  pump_suction_size_id : z.string().optional(),
  pump_suction_size : z.string().optional(),
  pump_suction_rating_id : z.string().optional(),
  pump_suction_rating : z.string().optional(),
  pump_discharge_size_id : z.string().optional(),
  pump_discharge_size : z.string().optional(),
  pump_discharge_rating_id : z.string().optional(),
  pump_discharge_rating : z.string().optional(),
  suction_pipe_data_id : z.string().optional(),
  suction_pipe_size : z.string().optional(),
  suction_pipe_sch : z.string().optional(),
  discharge_pipe_data_id : z.string().optional(),
  discharge_pipe_size : z.string().optional(),
  discharge_pipe_sch : z.string().optional(),
  suction_pipe_length : z.string().optional(),
  discharge_pipe_length_h : z.string().optional(),
  discharge_pipe_length_v : z.string().optional(),
  suction_pipe_id : z.string().optional(),
  suction_pipe_id_unit : z.string().optional(),
  discharge_pipe_id : z.string().optional(),
  discharge_pipe_id_unit : z.string().optional(),
  suction_elbow : z.string().optional(),
  suction_tee : z.string().optional(),
  suction_reducer : z.string().optional(),
  suction_valve : z.string().optional(),
  suction_y_strainer : z.string().optional(),
  suction_other : z.string().optional(),
  suction_equi_length : z.string().optional(),
  discharge_equi_length : z.string().optional(),
  discharge_elbow : z.string().optional(),
  discharge_tee : z.string().optional(),
  discharge_reducer : z.string().optional(),
  discharge_valve : z.string().optional(),
  discharge_y_strainer : z.string().optional(),
  discharge_other : z.string().optional(),
  /* Coupling Details */
  coup_type : z.string().optional(),
  /* Bearing Detail */
  bearing_nde_one_id : z.string().optional(),
  bearing_nde_one : z.string().optional(),
  bearing_nde_two_id : z.string().optional(),
  bearing_nde_two : z.string().optional(),
  bearing_lubric_type : z.string().optional(),
  bearing_lubric_brand : z.string().optional(),
  bearing_lubric_no : z.string().optional(),
  rotation_de : z.string().optional(),
  bearing_de_one_id : z.string().optional(),
  bearing_de_one : z.string().optional(),
  bearing_de_two_id : z.string().optional(),
  bearing_de_two : z.string().optional(),
  bearing_last_chg_dt : z.string().optional(),
});

export const PumpDetailLOVSchema = z.object({
  pump_brand : z.string().optional(),
  pump_model : z.string().optional(),
  model_size : z.string().optional(),
  pump_design : z.string().optional(),
  pump_standard : z.string().optional(),
  pump_standard_no : z.string().optional(),
  pump_impeller_type : z.string().optional(),
  pump_flange_con_std : z.string().optional(),
  pump_type : z.string().optional(),
  pump_stage : z.string().optional(),
  pump_seal_chamber : z.string().optional(),
  pump_oil_seal : z.string().optional(),
  pump_max_temp : z.string().optional(),
  pump_suction_size_id : z.string().optional(),
  pump_suction_size : z.string().optional(),
  pump_suction_rating_id : z.string().optional(),
  pump_suction_rating : z.string().optional(),
  pump_discharge_size_id : z.string().optional(),
  pump_discharge_size : z.string().optional(),
  pump_discharge_rating_id : z.string().optional(),
  pump_discharge_rating : z.string().optional(),
  created_at : z.string().optional(),
  created_by : z.string().optional(),
  updated_at : z.string().optional(),
  updated_by : z.string().optional(),
});

export const MotorDetailLOVSchema = z.object({
  motor_model : z.string().optional(),
  motor_serial_no : z.string().optional(),
  motor_brand : z.string().optional(),
  motor_drive : z.string().optional(),
  motor_standard : z.string().optional(),
  motor_ie : z.string().optional(),
  motor_speed : z.string().optional(),
  motor_speed_unit : z.string().optional(),
  motor_rated : z.string().optional(),
  motor_rated_unit : z.string().optional(),
  motor_factor : z.string().optional(),
  motor_connection : z.string().optional(),
  motor_phase : z.string().optional(),
  motor_efficiency : z.string().optional(),
  motor_efficiency_unit : z.string().optional(),
  motor_rated_current : z.string().optional(),
  motor_rated_current_unit : z.string().optional(),
});

export const ShaftSealLOVSchema = z.object({
  shaft_seal_design : z.string().optional(),
  shaft_seal_brand : z.string().optional(),
  shaft_seal_model : z.string().optional(),
  shaft_seal_material : z.string().optional(),
  mechanical_seal_api_plan : z.string().optional(),
});

export const PumpMatLOVSchema = z.object({
  pump_type_mat : z.string().optional(),
  pump_mat_code : z.string().optional(),
  casing_mat : z.string().optional(),
  casing_cover_mat : z.string().optional(),
  impeller_mat : z.string().optional(),
  liner_mat : z.string().optional(),
  base_mat : z.string().optional(),
  pump_head_mat : z.string().optional(),
  pump_head_cover_mat : z.string().optional(),
  stage_casing_diffuser_mat : z.string().optional(),
});

export const AddingUnitLOVSchema = z.object({
  unit_type: z.string().optional(),
  unit_name: z.string(),
  unit_value: z.string(),
  additional_1: z.string().optional(),
  additional_2: z.string().optional(),
  additional_3: z.string().optional(),
});
export const AddingPumpLOVSchema = z.object({
  data_type: z.string(),
  data_name: z.string(),
  data_value: z.string(),
  additional_1: z.string().optional(),
  additional_2: z.string().optional(),
  additional_3: z.string().optional(),
})

