from typing import Optional

from django.db import models
import uuid
from users.models import UserProfile 
from pump_data.models import PumpDetail

class EngineerReportCheck(models.Model):
    check_id = models.UUIDField(primary_key=True, editable=False , default=uuid.uuid4)
    pump_id = models.ForeignKey(PumpDetail, on_delete=models.SET_NULL,null=True)
    doc_customer = models.TextField(max_length=50, blank=True, null=True)
    doc_no = models.TextField(max_length=50, blank=True, null=True)
    doc_number_engineer = models.TextField(max_length=50, blank=True, null=True)
    status = models.TextField(max_length=50, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100,blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.CharField(max_length=100,blank=True, null=True)

    class Meta:
        db_table = 'tbl_engineer_report_check'

    def __str__(self):
        return f"{self.doc_customer}"

class EngineerReport(models.Model):
    report_id = models.UUIDField(primary_key=True, editable=False , default=uuid.uuid4)
    report_check_id = models.ForeignKey(EngineerReportCheck, on_delete=models.SET_NULL,null=True)
    pump_detail = models.ForeignKey(PumpDetail, on_delete=models.SET_NULL,null=True)
    user_detail = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,null=True)
    report_name = models.CharField(max_length=100 , blank=False, null=False)
    report_detail = models.CharField(max_length=100 , blank=True, null=True)
    remark = models.CharField(max_length=100 , blank=True, null=True)
    report_file = models.FileField(upload_to='reports/')
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100,blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.CharField(max_length=100,blank=True, null=True)
    class Meta:
        db_table = 'tbl_engineer_report'
    
    def __str__(self):
        return f"{self.report_name}"
    
class EngineerReportCheckCal(models.Model):
    check_cal_id = models.UUIDField(primary_key=True, editable=False , default=uuid.uuid4)
    check_id = models.ForeignKey(EngineerReportCheck, on_delete=models.CASCADE,null=True)

    test_speed = models.TextField(max_length=10, blank=True, null=True)
    test_speed_unit = models.TextField(max_length=10, blank=True, null=True)
    flow_ope = models.TextField(max_length=10, blank=True, null=True)
    flow_ope_unit = models.TextField(max_length=10, blank=True, null=True)
    suction_pres_ope = models.TextField(max_length=10, blank=True, null=True)
    suction_pres_ope_unit = models.TextField(max_length=10, blank=True, null=True)
    discharge_pres_ope = models.TextField(max_length=10, blank=True, null=True)
    discharge_pres_ope_unit = models.TextField(max_length=10, blank=True, null=True)
    diff_pres_ope = models.TextField(max_length=10, blank=True, null=True)
    diff_pres_ope_unit = models.TextField(max_length=100, blank=False, null=True)
    bearing_housing_temp = models.TextField(max_length=10, blank=False, null=True)
    bearing_housing_temp_unit = models.TextField(max_length=10, blank=True, null=True)
    current_i1_ope = models.TextField(max_length=10, blank=True, null=True)
    current_i1_ope_unit = models.TextField(max_length=10, blank=True, null=True)
    current_i2_ope = models.TextField(max_length=10, blank=True, null=True)
    current_i2_ope_unit = models.TextField(max_length=10, blank=True, null=True)
    current_i3_ope = models.TextField(max_length=10, blank=True, null=True)
    current_i3_ope_unit = models.TextField(max_length=10, blank=True, null=True)
    i_avg_ope = models.TextField(max_length=10, blank=True, null=True)
    i_avg_ope_unit = models.TextField(max_length=10, blank=True, null=True)
    v_avg_ope = models.TextField(max_length=10, blank=True, null=True)
    v_avg_ope_unit = models.TextField(max_length=10, blank=True, null=True)
    motor_power = models.TextField(max_length=10, blank=True, null=True)
    motor_power_unit = models.TextField(max_length=10, blank=True, null=True)
    shaft_ope = models.TextField(max_length=10, blank=True, null=True)
    shaft_ope_unit = models.TextField(max_length=10, blank=True, null=True)
    hyd_power_measure = models.TextField(max_length=10, blank=True, null=True)
    head_ope = models.TextField(max_length=10, blank=True, null=True)
    hyd_power_measure_unit = models.TextField(max_length=10, blank=True, null=True)
    head_ope_unit = models.TextField(max_length=10, blank=True, null=True)
    head_shut = models.TextField(max_length=10, blank=True, null=True)
    head_shut_unit = models.TextField(max_length=10, blank=True, null=True)
    head_max = models.TextField(max_length=10, blank=True, null=True)
    head_max_unit = models.TextField(max_length=10, blank=True, null=True)
    voltage_uv = models.TextField(max_length=10, blank=True, null=True)
    voltage_vw = models.TextField(max_length=10, blank=True, null=True)
    voltage_uw = models.TextField(max_length=10, blank=True, null=True)
    voltage_un = models.TextField(max_length=10, blank=True, null=True)
    voltage_vn = models.TextField(max_length=10, blank=True, null=True)
    voltage_wn = models.TextField(max_length=10, blank=True, null=True)
    insulation_uv = models.TextField(max_length=10, blank=True, null=True)
    insulation_winding_ux = models.TextField(max_length=10, blank=True, null=True)
    insulation_vw = models.TextField(max_length=10, blank=True, null=True)
    insulation_winding_vy = models.TextField(max_length=10, blank=True, null=True)
    insulation_uw = models.TextField(max_length=10, blank=True, null=True)
    insulation_winding_wz = models.TextField(max_length=10, blank=True, null=True)
    insulation_un = models.TextField(max_length=10, blank=True, null=True)
    insulation_vn = models.TextField(max_length=10, blank=True, null=True)
    insulation_wn = models.TextField(max_length=10, blank=True, null=True)
    current_u1 = models.TextField(max_length=10, blank=True, null=True)
    current_v1 = models.TextField(max_length=10, blank=True, null=True)
    current_w1 = models.TextField(max_length=10, blank=True, null=True)
    current_u2 = models.TextField(max_length=10, blank=True, null=True)
    current_v2 = models.TextField(max_length=10, blank=True, null=True)
    current_w2 = models.TextField(max_length=10, blank=True, null=True)
    Temp_u1 = models.TextField(max_length=10, blank=True, null=True)
    Temp_v1 = models.TextField(max_length=10, blank=True, null=True)
    Temp_w1 = models.TextField(max_length=10, blank=True, null=True)
    Temp_u2 = models.TextField(max_length=10, blank=True, null=True)
    Temp_v2 = models.TextField(max_length=10, blank=True, null=True)
    Temp_w2 = models.TextField(max_length=10, blank=True, null=True)
    env_temp = models.TextField(max_length=10, blank=True, null=True)
    env_temp_unit = models.TextField(max_length=10, blank=True, null=True)
    liquid_temp = models.TextField(max_length=10, blank=True, null=True)
    liquid_temp_unit = models.TextField(max_length=10, blank=True, null=True)
    npsha = models.TextField(max_length=10, blank=True, null=True)
    npsha_actual = models.TextField(max_length=10, blank=True, null=True)
    npsha_actual_unit = models.TextField(max_length=10, blank=True, null=True)
    suction_fluid_velo = models.TextField(max_length=10, blank=True, null=True)
    suction_fluid_velo_unit = models.TextField(max_length=10, blank=True, null=True)
    discharge_fluid_velo = models.TextField(max_length=10, blank=True, null=True)
    discharge_fluid_velo_unit = models.TextField(max_length=10, blank=True, null=True)
    remarks = models.TextField(max_length=100, blank=True, null=True)

    class Meta:
        db_table = 'tbl_engineer_report_check_cal'

    def __str__(self):
        return f"{self.check_id}"
    
class EngineerReportCheckVibration(models.Model):
    check_vibration_id = models.UUIDField(primary_key=True, editable=False , default=uuid.uuid4)
    check_id = models.ForeignKey(EngineerReportCheck, on_delete=models.CASCADE,null=True)
    
    pump_nde_x_date = models.TextField(max_length=50, blank=True, null=True)
    pump_nde_y_date = models.TextField(max_length=50, blank=True, null=True)
    pump_nde_z_date = models.TextField(max_length=50, blank=True, null=True)
    pump_de_x_date = models.TextField(max_length=50, blank=True, null=True)
    pump_de_y_date = models.TextField(max_length=50, blank=True, null=True)
    pump_de_z_date = models.TextField(max_length=50, blank=True, null=True)
    motor_nde_x_date = models.TextField(max_length=50, blank=True, null=True)
    motor_nde_y_date = models.TextField(max_length=50, blank=True, null=True)
    motor_nde_z_date = models.TextField(max_length=50, blank=True, null=True)
    motor_de_x_date = models.TextField(max_length=50, blank=True, null=True)
    motor_de_y_date = models.TextField(max_length=50, blank=True, null=True)
    motor_de_z_date = models.TextField(max_length=50, blank=True, null=True)
    v_pump_de_h = models.TextField(max_length=50, blank=True, null=True)
    v_pump_de_v = models.TextField(max_length=50, blank=True, null=True)
    v_pump_de_a = models.TextField(max_length=50, blank=True, null=True)
    v_pump_nde_h = models.TextField(max_length=50, blank=True, null=True)
    v_pump_nde_v = models.TextField(max_length=50, blank=True, null=True)
    v_pump_nde_a = models.TextField(max_length=50, blank=True, null=True)
    v_motor_de_h = models.TextField(max_length=50, blank=True, null=True)
    v_motor_de_v = models.TextField(max_length=50, blank=True, null=True)
    v_motor_de_a = models.TextField(max_length=50, blank=True, null=True)
    v_motor_nde_h = models.TextField(max_length=50, blank=True, null=True)
    v_motor_nde_v = models.TextField(max_length=50, blank=True, null=True)
    v_motor_nde_a = models.TextField(max_length=50, blank=True, null=True)
    a_pump_de_h = models.TextField(max_length=50, blank=True, null=True)
    a_pump_de_v = models.TextField(max_length=50, blank=True, null=True)
    a_pump_de_a = models.TextField(max_length=50, blank=True, null=True)
    a_pump_nde_h = models.TextField(max_length=50, blank=True, null=True)
    a_pump_nde_v = models.TextField(max_length=50, blank=True, null=True)
    a_pump_nde_a = models.TextField(max_length=50, blank=True, null=True)
    a_motor_de_h = models.TextField(max_length=50, blank=True, null=True)
    a_motor_de_v = models.TextField(max_length=50, blank=True, null=True)
    a_motor_de_a = models.TextField(max_length=50, blank=True, null=True)
    a_motor_nde_h = models.TextField(max_length=50, blank=True, null=True)
    a_motor_nde_v = models.TextField(max_length=50, blank=True, null=True)
    a_motor_nde_a = models.TextField(max_length=50, blank=True, null=True)
    temp_pump_nde = models.TextField(max_length=50, blank=True, null=True)
    d_pump_de_h = models.TextField(max_length=50, blank=True, null=True)
    d_pump_de_v = models.TextField(max_length=50, blank=True, null=True)
    d_pump_de_a = models.TextField(max_length=50, blank=True, null=True)
    d_pump_nde_h = models.TextField(max_length=50, blank=True, null=True)
    d_pump_nde_v = models.TextField(max_length=50, blank=True, null=True)
    d_pump_nde_a = models.TextField(max_length=50, blank=True, null=True)
    d_motor_de_h = models.TextField(max_length=50, blank=True, null=True)
    d_motor_de_v = models.TextField(max_length=50, blank=True, null=True)
    d_motor_de_a = models.TextField(max_length=50, blank=True, null=True)
    d_motor_nde_h = models.TextField(max_length=50, blank=True, null=True)
    d_motor_nde_v = models.TextField(max_length=50, blank=True, null=True)
    d_motor_nde_a = models.TextField(max_length=50, blank=True, null=True)
    temp_pump_de = models.TextField(max_length=50, blank=True, null=True)
    temp_motor_nde = models.TextField(max_length=50, blank=True, null=True)
    temp_motor_de = models.TextField(max_length=50, blank=True, null=True)
    env_vibration = models.TextField(max_length=50, blank=True, null=True)
    
    class Meta:
        db_table = 'tbl_engineer_report_check_vibration'

    def __str__(self):
        return f"{self.check_id}"
    
class StatusChoices(models.TextChoices):
        PASS = 'Pass', 'Pass'
        NOT_PASS = 'Not Pass', 'Not Pass'

class EngineerReportCheckVisual(models.Model):
    check_visual_id = models.UUIDField(primary_key=True, editable=False , default=uuid.uuid4)
    check_id = models.ForeignKey(EngineerReportCheck, on_delete=models.CASCADE,null=True)

    axial_hand_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    axial_hand_remark = models.TextField(max_length=100, blank=True, null=True)
    electricity_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    electricity_remark = models.TextField(max_length=100, blank=True, null=True)
    service_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    service_remark = models.TextField(max_length=100, blank=True, null=True)
    leakage_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    leakage_remark = models.TextField(max_length=100, blank=True, null=True)
    oil_grease_run_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    oil_grease_run_remark = models.TextField(max_length=100, blank=True, null=True)
    mechanical_run_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    mechanical_run_remark = models.TextField(max_length=100, blank=True, null=True)
    corrosion_run_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    corrosion_run_remark = models.TextField(max_length=100, blank=True, null=True)
    suction_valve_run_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    suction_valve_run_remark = models.TextField(max_length=100, blank=True, null=True)
    discharge_valve_run_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    discharge_valve_run_remark = models.TextField(max_length=100, blank=True, null=True)
    painting_run_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    painting_run_remark = models.TextField(max_length=100, blank=True, null=True)
    electric_connectivity_run_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    electric_connectivity_run_remark = models.TextField(max_length=100, blank=True, null=True)
    service_piping_run_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    service_piping_run_remark = models.TextField(max_length=100, blank=True, null=True)
    bolt_nut_run_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    bolt_nut_run_remark = models.TextField(max_length=100, blank=True, null=True)
    barrier_fluid_run_pres_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    barrier_fluid_run_pres_remark = models.TextField(max_length=100, blank=True, null=True)
    remarks_check = models.TextField(blank=True, null=True)

    bolt_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    bolt_remark = models.TextField(max_length=100, blank=True, null=True)
    electrical_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    electrical_remark = models.TextField(max_length=100, blank=True, null=True)
    corrosion_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    corrosion_remark = models.TextField(max_length=100, blank=True, null=True)
    oil_grease_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    oil_grease_remark = models.TextField(max_length=100, blank=True, null=True)
    oil_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    oil_remark = models.TextField(max_length=100, blank=True, null=True)
    painting_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    painting_remark = models.TextField(max_length=100, blank=True, null=True)
    cleanness_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    cleanness_remark = models.TextField(max_length=100, blank=True, null=True)
    chemical_clogging_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    chemical_clogging_remark = models.TextField(max_length=100, blank=True, null=True)
    suction_valve_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    suction_valve_remark = models.TextField(max_length=100, blank=True, null=True)
    discharge_valve_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    discharge_valve_remark = models.TextField(max_length=100, blank=True, null=True)
    hydraulic_air_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    hydraulic_air_remark = models.TextField(max_length=100, blank=True, null=True)
    air_supply_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    air_supply_remark = models.TextField(max_length=100, blank=True, null=True)
    air_filter_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    air_filter_remark = models.TextField(max_length=100, blank=True, null=True)
    air_filter_condense_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    air_filter_condense_remark = models.TextField(max_length=100, blank=True, null=True)
    mechanical_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    mechanical_remark = models.TextField(max_length=100, blank=True, null=True)
    coupling_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    coupling_remark = models.TextField(max_length=100, blank=True, null=True)
    gap_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    gap_remark = models.TextField(max_length=100, blank=True, null=True)
    seal_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    seal_remark = models.TextField(max_length=100, blank=True, null=True)
    alignment_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    alignment_remark = models.TextField(max_length=100, blank=True, null=True)
    rotate_hand_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    rotate_hand_remark = models.TextField(max_length=100, blank=True, null=True)
    rotating_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    rotating_remark = models.TextField(max_length=100, blank=True, null=True)
    noise_run_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    noise_run_remark = models.TextField(max_length=100, blank=True, null=True)
    noise_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    noise_remark = models.TextField(max_length=100, blank=True, null=True)
    oil_run_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    oil_run_remark = models.TextField(max_length=100, blank=True, null=True)
    leakage_run_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    leakage_run_remark = models.TextField(max_length=100, blank=True, null=True)
    impeller_stutter_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    impeller_stutter_remark = models.TextField(max_length=100, blank=True, null=True)
    cavitation_run_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    cavitation_run_remark = models.TextField(max_length=100, blank=True, null=True)
    other_leakage_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    other_leakage_remark = models.TextField(max_length=100, blank=True, null=True)
    non_re_valve_check = models.CharField(max_length=10, blank=True, null=True, choices=StatusChoices.choices, default=StatusChoices.NOT_PASS)
    non_re_valve_remark = models.TextField(max_length=100, blank=True, null=True)

    class Meta:
        db_table = 'tbl_engineer_report_check_visual'

    def __str__(self):
        return f"{self.check_id}"
    
class EngineerReportCheckResult(models.Model):
    check_result_id = models.UUIDField(primary_key=True, editable=False , default=uuid.uuid4)
    check_id = models.ForeignKey(EngineerReportCheck, on_delete=models.CASCADE,null=True)
    
    speed_suggest = models.TextField(max_length=100, blank=True, null=True)
    flow_suggest = models.TextField(max_length=100, blank=True, null=True)
    npshr_suggest = models.TextField(max_length=100, blank=True, null=True)
    velocity_suggest = models.TextField(max_length=100, blank=True, null=True)
    boiling_point_suggest = models.TextField(max_length=100, blank=True, null=True)
    current_suggest = models.TextField(max_length=100, blank=True, null=True)
    power_suggest = models.TextField(max_length=100, blank=True, null=True)
    api_suggest = models.TextField(max_length=100, blank=True, null=True)
    buffer_suggest = models.TextField(max_length=100, blank=True, null=True)
    bearing_suggest = models.TextField(max_length=100, blank=True, null=True)
    vibration_suggest = models.TextField(max_length=100, blank=True, null=True)
    bearing_temp_suggest = models.TextField(max_length=100, blank=True, null=True)
    timestamp = models.TextField(max_length=100, blank=True, null=True)
    range_30_110_result = models.TextField(max_length=100, blank=True, null=True)
    range_30_110_suggest = models.TextField(max_length=100, blank=True, null=True)
    range_30_110_remark = models.TextField(max_length=100, blank=True, null=True)
    npshr_npsha_result = models.TextField(max_length=100, blank=True, null=True)
    npshr_npsha_suggest = models.TextField(max_length=100, blank=True, null=True)
    npshr_npsha_remark = models.TextField(max_length=100, blank=True, null=True)
    pump_standard_result = models.TextField(max_length=100, blank=True, null=True)
    pump_standard_suggest = models.TextField(max_length=100, blank=True, null=True)
    pump_standard_remark = models.TextField(max_length=100, blank=True, null=True)
    power_result = models.TextField(max_length=100, blank=True, null=True)
    power_remark = models.TextField(max_length=100, blank=True, null=True)
    fluid_temp_result = models.TextField(max_length=100, blank=True, null=True)
    fluid_temp_suggest = models.TextField(max_length=100, blank=True, null=True)
    fluid_temp_remark = models.TextField(max_length=100, blank=True, null=True)
    bearing_temp_result = models.TextField(max_length=100, blank=True, null=True)
    bearing_temp_remark = models.TextField(max_length=100, blank=True, null=True)
    v_pump_de_h_result = models.TextField(max_length=100, blank=True, null=True)
    v_pump_de_v_result = models.TextField(max_length=100, blank=True, null=True)
    v_pump_de_a_result = models.TextField(max_length=100, blank=True, null=True)
    v_pump_nde_h_result = models.TextField(max_length=100, blank=True, null=True)
    v_pump_nde_v_result = models.TextField(max_length=100, blank=True, null=True)
    v_pump_nde_a_result = models.TextField(max_length=100, blank=True, null=True)
    v_motor_de_h_result = models.TextField(max_length=100, blank=True, null=True)
    v_motor_de_v_result = models.TextField(max_length=100, blank=True, null=True)
    v_motor_de_a_result = models.TextField(max_length=100, blank=True, null=True)
    v_motor_nde_h_result = models.TextField(max_length=100, blank=True, null=True)
    v_motor_nde_v_result = models.TextField(max_length=100, blank=True, null=True)
    v_motor_nde_a_result = models.TextField(max_length=100, blank=True, null=True)
    a_pump_de_h_result = models.TextField(max_length=100, blank=True, null=True)
    a_pump_de_v_result = models.TextField(max_length=100, blank=True, null=True)
    a_pump_de_a_result = models.TextField(max_length=100, blank=True, null=True)
    a_pump_nde_h_result = models.TextField(max_length=100, blank=True, null=True)
    a_pump_nde_v_result = models.TextField(max_length=100, blank=True, null=True)
    a_pump_nde_a_result = models.TextField(max_length=100, blank=True, null=True)
    a_motor_de_h_result = models.TextField(max_length=100, blank=True, null=True)
    a_motor_de_v_result = models.TextField(max_length=100, blank=True, null=True)
    a_motor_de_a_result = models.TextField(max_length=100, blank=True, null=True)
    a_motor_nde_h_result = models.TextField(max_length=100, blank=True, null=True)
    a_motor_nde_v_result = models.TextField(max_length=100, blank=True, null=True)
    a_motor_nde_a_result = models.TextField(max_length=100, blank=True, null=True)
    v_pump_suggest = models.TextField(max_length=100, blank=True, null=True)
    v_pump_remark = models.TextField(max_length=100, blank=True, null=True)
    v_motor_suggest = models.TextField(max_length=100, blank=True, null=True)
    v_motor_remark = models.TextField(max_length=100, blank=True, null=True)
    a_pump_suggest = models.TextField(max_length=100, blank=True, null=True)
    a_pump_remark = models.TextField(max_length=100, blank=True, null=True)
    a_motor_suggest = models.TextField(max_length=100, blank=True, null=True)
    a_motor_remark = models.TextField(max_length=100, blank=True, null=True)

    class Meta:
        db_table = 'tbl_engineer_report_check_result'

    def __str__(self):
        return f"{self.check_id}"