# Generated by Django 5.1.5 on 2025-02-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryCurve',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('fac_number', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model_short', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('data_type', models.CharField(blank=True, max_length=100, null=True)),
                ('se_quence', models.CharField(blank=True, max_length=100, null=True)),
                ('rpm', models.CharField(blank=True, max_length=100, null=True)),
                ('imp_dia', models.CharField(blank=True, max_length=100, null=True)),
                ('flow', models.CharField(blank=True, max_length=100, null=True)),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('eff', models.CharField(blank=True, max_length=100, null=True)),
                ('npshr', models.CharField(blank=True, max_length=100, null=True)),
                ('kw', models.CharField(blank=True, max_length=100, null=True)),
                ('curve_format', models.CharField(blank=True, max_length=100, null=True)),
                ('eff_rl', models.CharField(blank=True, max_length=100, null=True)),
                ('eff_status', models.CharField(blank=True, max_length=100, null=True)),
                ('eff_distance', models.CharField(blank=True, max_length=100, null=True)),
                ('tolerance', models.CharField(blank=True, max_length=100, null=True)),
                ('scale_xy', models.CharField(blank=True, max_length=100, null=True)),
                ('update_time', models.CharField(blank=True, max_length=100, null=True)),
                ('dry_sat', models.CharField(blank=True, max_length=100, null=True)),
                ('liquid', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_factory_curve',
            },
        ),
    ]
