# Generated by Django 5.1.5 on 2025-03-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_curve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryCurveNumber',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('fac_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_factory_curve_number',
            },
        ),
    ]
