# Generated by Django 5.1.5 on 2025-03-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_curve', '0002_factorycurvenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorycurvenumber',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factorycurvenumber',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factorycurvenumber',
            name='model_short',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factorycurvenumber',
            name='rpm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
