# Generated by Django 5.1.5 on 2025-06-09 01:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pump_data', '0016_alter_pumpdetail_company_id_and_more'),
        ('users', '0003_alter_companiesdetail_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=100)),
                ('report_file', models.FileField(upload_to='report/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('pump_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pump_data.pumpdetail')),
                ('user_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userprofile')),
            ],
            options={
                'db_table': 'tbl_engineer_report',
            },
        ),
    ]
