# Generated by Django 5.1.5 on 2025-06-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerreport',
            name='report_file',
            field=models.FileField(max_length=1000, upload_to='report/'),
        ),
    ]
