# Generated by Django 5.1.5 on 2025-06-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0002_alter_engineerreport_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerreport',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='engineerreport',
            name='report_detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
