# Generated by Django 5.1.5 on 2026-03-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0002_engineerreport_remark_engineerreport_report_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerreport',
            name='report_file',
            field=models.FileField(upload_to='reports/'),
        ),
    ]
