# Generated by Django 5.1.5 on 2025-07-02 09:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0003_engineerreport_remark_engineerreport_report_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerReportCheck',
            fields=[
                ('check_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_customer', models.TextField(blank=True, max_length=50, null=True)),
                ('doc_no', models.TextField(blank=True, max_length=50, null=True)),
                ('doc_number_engineer', models.TextField(blank=True, max_length=50, null=True)),
                ('timestamp', models.TextField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_engineer_report_check',
            },
        ),
    ]
