# Generated by Django 5.1.5 on 2026-03-30 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0003_alter_engineerreport_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerreport',
            name='report_check_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='engineer.engineerreportcheck'),
        ),
    ]
