# Generated by Django 5.1.5 on 2025-07-03 01:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0004_engineerreportcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerReportCheckCal',
            fields=[
                ('check_cal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_speed', models.FloatField(blank=True, null=True)),
                ('test_speed_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('flow_ope', models.FloatField(blank=True, null=True)),
                ('flow_ope_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('suction_pres_ope', models.FloatField(blank=True, null=True)),
                ('suction_pres_ope_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('discharge_pres_ope', models.FloatField(blank=True, null=True)),
                ('discharge_pres_ope_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('diff_pres_ope', models.FloatField(blank=True, null=True)),
                ('diff_pres_ope_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('current_i1_ope', models.FloatField(blank=True, null=True)),
                ('current_i1_ope_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('current_i2_ope', models.FloatField(blank=True, null=True)),
                ('current_i2_ope_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('current_i3_ope', models.FloatField(blank=True, null=True)),
                ('current_i3_ope_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('i_avg_ope', models.FloatField(blank=True, null=True)),
                ('i_avg_ope_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('v_avg_ope', models.FloatField(blank=True, null=True)),
                ('v_avg_ope_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('motor_power', models.FloatField(blank=True, null=True)),
                ('motor_power_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('shaft_ope', models.FloatField(blank=True, null=True)),
                ('shaft_ope_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('head_ope', models.FloatField(blank=True, null=True)),
                ('head_ope_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('head_shut', models.FloatField(blank=True, null=True)),
                ('head_shut_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('head_max', models.FloatField(blank=True, null=True)),
                ('head_max_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('check_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engineer.engineerreportcheck')),
            ],
            options={
                'db_table': 'tbl_engineer_report_check_cal',
            },
        ),
    ]
