# Generated by Django 5.1.5 on 2026-04-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0005_engineerreportcheckvisual_air_filter_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerreportcheckvisual',
            name='remarks_check',
            field=models.TextField(blank=True, null=True),
        ),
    ]
