# Generated by Django 5.1.5 on 2025-07-03 04:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0005_engineerreportcheckcal'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerReportCheckVibration',
            fields=[
                ('check_vibration_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('v_pump_de_h', models.FloatField(blank=True, null=True)),
                ('v_pump_de_h_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('v_pump_de_v', models.FloatField(blank=True, null=True)),
                ('v_pump_de_v_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('v_pump_de_a', models.FloatField(blank=True, null=True)),
                ('v_pump_de_a_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('v_pump_nde_h', models.FloatField(blank=True, null=True)),
                ('v_pump_nde_h_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('v_pump_nde_v', models.FloatField(blank=True, null=True)),
                ('v_pump_nde_v_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('v_pump_nde_a', models.FloatField(blank=True, null=True)),
                ('v_pump_nde_a_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('v_motor_de_h', models.FloatField(blank=True, null=True)),
                ('v_motor_de_h_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('v_motor_de_v', models.FloatField(blank=True, null=True)),
                ('v_motor_de_v_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('v_motor_de_a', models.FloatField(blank=True, null=True)),
                ('v_motor_de_a_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('v_motor_nde_h', models.FloatField(blank=True, null=True)),
                ('v_motor_nde_h_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('v_motor_nde_v', models.FloatField(blank=True, null=True)),
                ('v_motor_nde_v_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('v_motor_nde_a', models.FloatField(blank=True, null=True)),
                ('v_motor_nde_a_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('a_pump_de_h', models.FloatField(blank=True, null=True)),
                ('a_pump_de_h_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('a_pump_de_v', models.FloatField(blank=True, null=True)),
                ('a_pump_de_v_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('a_pump_de_a', models.FloatField(blank=True, null=True)),
                ('a_pump_de_a_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('a_pump_nde_h', models.FloatField(blank=True, null=True)),
                ('a_pump_nde_h_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('a_pump_nde_v', models.FloatField(blank=True, null=True)),
                ('a_pump_nde_v_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('a_pump_nde_a', models.FloatField(blank=True, null=True)),
                ('a_pump_nde_a_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('a_motor_de_h', models.FloatField(blank=True, null=True)),
                ('a_motor_de_h_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('a_motor_de_v', models.FloatField(blank=True, null=True)),
                ('a_motor_de_v_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('a_motor_de_a', models.FloatField(blank=True, null=True)),
                ('a_motor_de_a_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('a_motor_nde_h', models.FloatField(blank=True, null=True)),
                ('a_motor_nde_h_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('a_motor_nde_v', models.FloatField(blank=True, null=True)),
                ('a_motor_nde_v_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('a_motor_nde_a', models.FloatField(blank=True, null=True)),
                ('a_motor_nde_a_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('temp_pump_nde', models.FloatField(blank=True, null=True)),
                ('temp_pump_nde_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('temp_pump_de', models.FloatField(blank=True, null=True)),
                ('temp_pump_de_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('temp_motor_nde', models.FloatField(blank=True, null=True)),
                ('temp_motor_nde_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('temp_motor_de', models.FloatField(blank=True, null=True)),
                ('temp_motor_de_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('env_vibration', models.FloatField(blank=True, null=True)),
                ('env_vibration_unit', models.TextField(blank=True, max_length=10, null=True)),
                ('check_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engineer.engineerreportcheck')),
            ],
            options={
                'db_table': 'tbl_engineer_report_check_vibration',
            },
        ),
    ]
