# Generated by Django 5.1.5 on 2025-07-03 08:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0006_engineerreportcheckvibration'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='discharge_fluid_velo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='discharge_fluid_velo_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='env_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='env_temp_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='liquid_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='liquid_temp_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='npsha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='npsha_actual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='npsha_actual_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='npsha_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='remarks',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='suction_fluid_velo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='suction_fluid_velo_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='EngineerReportCheckVisual',
            fields=[
                ('check_visual_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alignment_check', models.TextField(blank=True, max_length=50, null=True)),
                ('coupling_check', models.TextField(blank=True, max_length=50, null=True)),
                ('suction_valve_check', models.TextField(blank=True, max_length=50, null=True)),
                ('rotate_hand_check', models.TextField(blank=True, max_length=50, null=True)),
                ('axial_hand_check', models.TextField(blank=True, max_length=50, null=True)),
                ('gap_check', models.TextField(blank=True, max_length=50, null=True)),
                ('discharge_valve_check', models.TextField(blank=True, max_length=50, null=True)),
                ('bolt_check', models.TextField(blank=True, max_length=50, null=True)),
                ('oil_grease_check', models.TextField(blank=True, max_length=50, null=True)),
                ('electricity_check', models.TextField(blank=True, max_length=50, null=True)),
                ('service_check', models.TextField(blank=True, max_length=50, null=True)),
                ('leakage_check', models.TextField(blank=True, max_length=50, null=True)),
                ('corrosion_check', models.TextField(blank=True, max_length=50, null=True)),
                ('painting_check', models.TextField(blank=True, max_length=50, null=True)),
                ('noise_run_check', models.TextField(blank=True, max_length=50, null=True)),
                ('oil_grease_run_check', models.TextField(blank=True, max_length=50, null=True)),
                ('leakage_run_check', models.TextField(blank=True, max_length=50, null=True)),
                ('mechanical_run_check', models.TextField(blank=True, max_length=50, null=True)),
                ('cavitation_run_check', models.TextField(blank=True, max_length=50, null=True)),
                ('corrosion_run_check', models.TextField(blank=True, max_length=50, null=True)),
                ('suction_valve_run_check', models.TextField(blank=True, max_length=50, null=True)),
                ('discharge_valve_run_check', models.TextField(blank=True, max_length=50, null=True)),
                ('painting_run_check', models.TextField(blank=True, max_length=50, null=True)),
                ('electric_connectivity_run_check', models.TextField(blank=True, max_length=50, null=True)),
                ('service_piping_run_check', models.TextField(blank=True, max_length=50, null=True)),
                ('bolt_nut_run_check', models.TextField(blank=True, max_length=50, null=True)),
                ('barrier_fluid_run_pres_check', models.TextField(blank=True, max_length=50, null=True)),
                ('remarks_check', models.TextField(blank=True, max_length=50, null=True)),
                ('alignment_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('coupling_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('suction_valve_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('painting_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('rotating_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('axial_hand_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('gap_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('discharge_valve_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('bolt_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('oil_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('electricity_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('service_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('leakage_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('corrosion_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('noise_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('noise_run_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('oil_run_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('leakage_run_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('mechanical_run_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('cavitation_run_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('corrosion_run_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('suction_valve_run_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('discharge_valve_run_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('painting_run_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('electric_connectivity_run_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('service_piping_run_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('bolt_nut_run_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('barrier_fluid_run_pres_remark', models.TextField(blank=True, max_length=50, null=True)),
                ('check_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engineer.engineerreportcheck')),
            ],
            options={
                'db_table': 'tbl_engineer_report_check_visual',
            },
        ),
    ]
