# Generated by Django 5.1.5 on 2026-04-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0006_alter_engineerreportcheckvisual_remarks_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='d_motor_de_a',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='d_motor_de_a_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='d_motor_de_h',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='d_motor_de_h_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='d_motor_de_v',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='d_motor_de_v_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='d_motor_nde_a',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='d_motor_nde_a_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='d_motor_nde_h',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='d_motor_nde_h_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='d_motor_nde_v',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='d_motor_nde_v_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='d_pump_de_a',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='d_pump_de_a_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='d_pump_de_h',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='d_pump_de_h_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='d_pump_de_v',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='d_pump_de_v_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='d_pump_nde_a',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='d_pump_nde_a_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='d_pump_nde_h',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='d_pump_nde_h_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='d_pump_nde_v',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='d_pump_nde_v_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
