# Generated by Django 5.1.5 on 2025-07-11 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0008_engineerreportcheckresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineerreportcheck',
            old_name='timestamp',
            new_name='status',
        ),
    ]
