# Generated by Django 5.1.5 on 2026-06-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0008_remove_engineerreportcheckcal_npsha_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='motor_de_x_date',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='motor_de_y_date',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='motor_de_z_date',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='motor_nde_x_date',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='motor_nde_y_date',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='motor_nde_z_date',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='pump_de_x_date',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='pump_de_y_date',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='pump_de_z_date',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='pump_nde_x_date',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='pump_nde_y_date',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckvibration',
            name='pump_nde_z_date',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='a_motor_de_a',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='a_motor_de_h',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='a_motor_de_v',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='a_motor_nde_a',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='a_motor_nde_h',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='a_motor_nde_v',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='a_pump_de_a',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='a_pump_de_h',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='a_pump_de_v',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='a_pump_nde_a',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='a_pump_nde_h',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='a_pump_nde_v',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='d_motor_de_a',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='d_motor_de_h',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='d_motor_de_v',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='d_motor_nde_a',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='d_motor_nde_h',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='d_motor_nde_v',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='d_pump_de_a',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='d_pump_de_h',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='d_pump_de_v',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='d_pump_nde_a',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='d_pump_nde_h',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='d_pump_nde_v',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='env_vibration',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='env_vibration_unit',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='temp_motor_de',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='temp_motor_de_unit',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='temp_motor_nde',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='temp_motor_nde_unit',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='temp_pump_de',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='temp_pump_de_unit',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='temp_pump_nde',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='temp_pump_nde_unit',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='v_motor_de_a',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='v_motor_de_h',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='v_motor_de_v',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='v_motor_nde_a',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='v_motor_nde_h',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='v_motor_nde_v',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='v_pump_de_a',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='v_pump_de_h',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='v_pump_de_v',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='v_pump_nde_a',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='v_pump_nde_h',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='v_pump_nde_v',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
