# Generated by Django 5.1.5 on 2026-06-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0009_engineerreportcheckvibration_motor_de_x_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineerreportcheckvibration',
            name='env_vibration_unit',
        ),
        migrations.RemoveField(
            model_name='engineerreportcheckvibration',
            name='temp_motor_de_unit',
        ),
        migrations.RemoveField(
            model_name='engineerreportcheckvibration',
            name='temp_motor_nde_unit',
        ),
        migrations.RemoveField(
            model_name='engineerreportcheckvibration',
            name='temp_pump_de_unit',
        ),
        migrations.RemoveField(
            model_name='engineerreportcheckvibration',
            name='temp_pump_nde_unit',
        ),
    ]
