# Generated by Django 5.1.5 on 2025-07-14 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0009_rename_timestamp_engineerreportcheck_status'),
        ('pump_data', '0021_rename_brand_pumpdetail_address_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerreportcheck',
            name='pump_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pump_data.pumpdetail'),
        ),
    ]
