# Generated by Django 5.1.5 on 2025-07-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0010_engineerreportcheck_pump_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerreportcheckvisual',
            name='noise_check',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
