# Generated by Django 5.1.5 on 2025-07-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0011_engineerreportcheckvisual_noise_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerreportcheckcal',
            name='current_i1_ope',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckcal',
            name='current_i2_ope',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckcal',
            name='current_i3_ope',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckcal',
            name='diff_pres_ope',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckcal',
            name='discharge_fluid_velo',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckcal',
            name='discharge_pres_ope',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckcal',
            name='env_temp',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckcal',
            name='flow_ope',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckcal',
            name='head_max',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckcal',
            name='head_ope',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckcal',
            name='head_shut',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckcal',
            name='i_avg_ope',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckcal',
            name='liquid_temp',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckcal',
            name='motor_power',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckcal',
            name='npsha',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckcal',
            name='npsha_actual',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckcal',
            name='shaft_ope',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckcal',
            name='suction_fluid_velo',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckcal',
            name='suction_pres_ope',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckcal',
            name='test_speed',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckcal',
            name='v_avg_ope',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='a_motor_de_a',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='a_motor_de_h',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='a_motor_de_v',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='a_motor_nde_a',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='a_motor_nde_h',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='a_motor_nde_v',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='a_pump_de_a',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='a_pump_de_h',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='a_pump_de_v',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='a_pump_nde_a',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='a_pump_nde_h',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='a_pump_nde_v',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='env_vibration',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='temp_motor_de',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='temp_motor_nde',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='temp_pump_de',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='temp_pump_nde',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='v_motor_de_a',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='v_motor_de_h',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='v_motor_de_v',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='v_motor_nde_a',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='v_motor_nde_h',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='v_motor_nde_v',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='v_pump_de_a',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='v_pump_de_h',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='v_pump_de_v',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='v_pump_nde_a',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='v_pump_nde_h',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckvibration',
            name='v_pump_nde_v',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
