# Generated by Django 5.1.5 on 2025-10-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0012_alter_engineerreportcheckcal_current_i1_ope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='Temp_u1',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='Temp_u2',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='Temp_v1',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='Temp_v2',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='Temp_w1',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='Temp_w2',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='current_u1',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='current_u2',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='current_v1',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='current_v2',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='current_w1',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='current_w2',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='insulation_un',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='insulation_uv',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='insulation_uw',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='insulation_vn',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='insulation_vw',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='insulation_winding_ux',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='insulation_winding_uz',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='insulation_winding_vy',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='insulation_wn',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='voltage_un',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='voltage_uv',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='voltage_uw',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='voltage_vn',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='voltage_vw',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='voltage_wn',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
