# Generated by Django 5.1.5 on 2025-10-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0013_engineerreportcheckcal_temp_u1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='hyd_power_meassure',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='hyd_power_meassure_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
