# Generated by Django 5.1.5 on 2025-10-15 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0014_engineerreportcheckcal_hyd_power_meassure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineerreportcheckcal',
            old_name='insulation_winding_uz',
            new_name='insulation_winding_wz',
        ),
    ]
