# Generated by Django 5.1.5 on 2025-10-29 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0015_rename_insulation_winding_uz_engineerreportcheckcal_insulation_winding_wz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerreportcheckresult',
            name='check_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engineer.engineerreportcheck'),
        ),
    ]
