# Generated by Django 5.1.5 on 2026-02-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0016_alter_engineerreportcheckresult_check_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='bearing_housing_temp',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineerreportcheckcal',
            name='bearing_housing_temp_unit',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineerreportcheckcal',
            name='diff_pres_ope_unit',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
