# Generated by Django 5.1.5 on 2025-06-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companiesdetail',
            old_name='customer_id',
            new_name='company_id',
        ),
    ]
