# Generated by Django 5.0.6 on 2024-07-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_user_id_customuser_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="user_email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="user_auth",
            new_name="phone",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="user_phone",
            new_name="role",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="user_name",
            new_name="username",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="user_password",
        ),
    ]
