# Generated by Django 5.1.5 on 2025-06-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_customer_id_companiesdetail_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companiesdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='companiesdetail',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companiesdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='companiesdetail',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
