# Generated by Django 5.1.5 on 2026-02-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_companiesdetail_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Developer', 'Developer'), ('Sales', 'Sales'), ('Service', 'Service'), ('Engineer', 'Engineer'), ('Customer', 'Customer')], max_length=30),
        ),
    ]
