# Generated by Django 5.1.3 on 2025-01-14 09:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_lastname_remove_customuser_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompaniesDetail',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_code', models.CharField(max_length=100)),
                ('customer_industry_id', models.CharField(max_length=100)),
                ('customer_industry_group', models.CharField(max_length=100)),
                ('company_name_en', models.CharField(max_length=100)),
                ('address_en', models.CharField(max_length=100)),
                ('company_name_th', models.CharField(max_length=100)),
                ('address_th', models.CharField(max_length=100)),
                ('map', models.CharField(max_length=100)),
                ('province_th', models.CharField(max_length=100)),
                ('province_en', models.CharField(max_length=100)),
                ('sales_area', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_company_detail',
            },
        ),
        migrations.CreateModel(
            name='ContactPersonDetail',
            fields=[
                ('contact_person_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_code', models.CharField(max_length=100)),
                ('name_surname_en', models.CharField(max_length=100)),
                ('name_surname_th', models.CharField(max_length=100)),
                ('position_en', models.CharField(max_length=100)),
                ('position_th', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_contact_person_detail',
            },
        ),
    ]
