# Generated by Django 5.1.5 on 2025-01-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_companiesdetail_contactpersondetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companiesdetail',
            old_name='province_en',
            new_name='province',
        ),
        migrations.RemoveField(
            model_name='companiesdetail',
            name='province_th',
        ),
        migrations.AlterField(
            model_name='companiesdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='companiesdetail',
            name='customer_industry_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companiesdetail',
            name='customer_industry_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companiesdetail',
            name='map',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companiesdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contactpersondetail',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contactpersondetail',
            name='time_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
