# Generated by Django 5.1.5 on 2025-01-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_province_en_companiesdetail_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companiesdetail',
            name='address_en',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='companiesdetail',
            name='address_th',
            field=models.CharField(max_length=1000),
        ),
    ]
