# Generated by Django 5.1.5 on 2025-01-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_companiesdetail_address_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_customer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
