# Generated by Django 5.1.5 on 2025-01-28 04:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userprofile_user_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PECPersonDetail',
            fields=[
                ('pec_person_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pec_person_code', models.CharField(max_length=100)),
                ('name_surname_en', models.CharField(max_length=100)),
                ('name_surname_th', models.CharField(max_length=100)),
                ('position_en', models.CharField(max_length=100)),
                ('position_th', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
