# Generated by Django 5.1.5 on 2025-02-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_pecpersondetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactPersonDetail',
        ),
        migrations.DeleteModel(
            name='PECPersonDetail',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='username',
            new_name='user_username',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_image',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='lastname',
            new_name='user_company_code',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='surname',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='user_role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_customer',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_mobile',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_pec_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_tel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='tbl_user',
        ),
    ]
